- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/xcshareddata/xcschemes/secant-testnet.xcscheme
- secant/App Errors/AppError.swift
- secant/Mocked Dependencies/KeyStoring.swift
- secant/Routers/AppRouter.swift
- secant/Screens/Error/InitFailedScreen.swift
- secant/Screens/Error/InitFailedScreenViewModel.swift
- secant/Screens/Loading/LoadingScreen.swift
- secant/Screens/Loading/LoadingScreenViewModel.swift
- secant/Stubs/MockServices.swift
- secantTests/LoadingScreenTests.swift
> Loading Screen + Tests

- secant/UI Components/Chips/EnumeratedChip.swift
- secant/UI Components/DesignGuide.swift
Closes #59 
The Design Guide Preview is a constant work in progress.
It contains certain placeholders, and it's ok. Those are still in the making. Once they are done, they should be added to the guide in the corresponding places.
> Design guide preview

- secant/Features/Onboarding/OnboardingStore.swift
- secant/Features/Onboarding/Views/Onboarding.swift
- secantTests/OnboardingTests/OnboardingStoreTests.swift
This PR makes some updates to the onboarding state machine, calculating an offset based on the index vs manually incrementing and decrementing that value.  Also, this PR adds unit tests for the guard cases in incrementing and decrementing, where going below 0 is not allowed and results in no changes, or going above the total number of steps is also not allowed and results in no changes.
> Onboarding State Updates

- secant/UI Components/Buttons/NavigationButtonStyle.swift
- secant/UI Components/DesignGuide.swift
While working through onboarding and a bug in Xcode / MacOS, I came across some updates and cleanup that could be done in the Design Guide so I threw a PR together quick to get it up to date.
> Design Guide Updates

- secant.xcodeproj/project.pbxproj
- secant/Features/Home/Views/HomeView.swift
- secant/Features/Onboarding/OnboardingStore.swift
- secant/Features/Onboarding/Views/Onboarding.swift
- secant/Screens/Onboarding/OnboardingContentView.swift
- secant/Screens/Onboarding/OnboardingFooterView.swift
- secant/Screens/Onboarding/OnboardingHeaderView.swift
- secant/Screens/Onboarding/OnboardingScreen.swift
- secant/UI Components/CircularFrame/CircularFrame.swift
- secant/UI Components/CircularFrame/CircularFrameBackground.swift
- secant/UI Components/CircularFrame/CircularFrameBadge.swift
- secant/Util/WithStateBinding.swift
- secantTests/OnboardingTests/OnboardingStoreTests.swift
> Onboarding Screen

- secant.xcodeproj/project.pbxproj
- secant/Features/Home/HomeStore.swift
- secant/Features/Home/Views/HomeView.swift
This PR is just to have a show and tell build on testflight.
> Integrate onboarding to fake home

- secant/Features/BackupFlow/RecoveryPhraseDisplayStore.swift
- secant/Features/BackupFlow/Views/RecoveryPhraseDisplayView.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Send/SendStore.swift
- secant/Features/Send/Views/SentView.swift
- secant/SecantApp.swift
- secantTests/BackupFlowTests/RecoveryPhraseDisplayReducerTests.swift
This PR adds a testable pasteboard to the recovery phrase display and cleans up some lint warnings.  Also of note, this PR updates an existing test that always passed, to using an initial store value that proves the functionality does work.
Closes [#128](https://app.zenhub.com/workspaces/wallet-5db8aa0244512d0001e0968e/issues/zcash/secant-ios-wallet/128)
> Testable Pasteboard

- secant/Features/Home/HomeStore.swift
- secant/Features/Home/Views/HomeView.swift
Add back in the ability to navigate to the `History` placeholder, lost it in a rebase 😭. (And a little code cleanup).
| Before | After (ignore gif graininess please 😅) |
| --- | --- |
| ![Simulator Screen Shot - iPhone 13 - 2021-12-14 at 23 05 36](https://user-images.githubusercontent.com/90868897/146093462-b0265f43-fc0e-433b-a466-a785a6e94f3e.png) | ![out](https://user-images.githubusercontent.com/90868897/146093633-7f897cb5-6158-4f28-99b9-a1266b9844d7.gif) 
---
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review …
> Add link to history from `Home`

- secant.xcodeproj/project.pbxproj
- secant/Colors.xcassets/Text/captionText.colorset/Contents.json
- secant/Colors.xcassets/Text/captionTextShadow.colorset/Contents.json
- secant/Colors.xcassets/ZcashBadge/Contents.json
- secant/Colors.xcassets/ZcashBadge/ZcashLogoFill.colorset/Contents.json
- secant/Colors.xcassets/ZcashBadge/innerCircle.colorset/Contents.json
- secant/Colors.xcassets/ZcashBadge/outerRingGradientEnd.colorset/Contents.json
- secant/Colors.xcassets/ZcashBadge/outerRingGradientStart.colorset/Contents.json
- secant/Colors.xcassets/ZcashBadge/shadowColor.colorset/Contents.json
- secant/Colors.xcassets/ZcashBadge/thickRing.colorset/Contents.json
- secant/Colors.xcassets/ZcashBadge/thinRing.colorset/Contents.json
- secant/Features/App/App.swift
- secant/Features/App/Views/AppView.swift
- secant/Features/Welcome/WelcomeView.swift
- secant/Generated/XCAssets+Generated.swift
- secant/UIComponents/Backgrounds/ScreenBackground.swift
- secant/UIComponents/Extensions/ConditionalModifier.swift
- secant/UIComponents/FontStyles/SecantTextStyles.swift
- secant/UIComponents/Shapes/ZcashSymbol.swift
Note: this PR is mergint the same code as, but on a cleaner branch from current main.
https://github.com/zcash/secant-ios-wallet/pull/142
closes #61 
> Issue #61 - Zcash Logo and welcome screen

- README.md
Installations done via homebrew endup on a different path compared to Intel machines. A section describing how to handle both Swiftlint & Swiftgen on Apple Silicon added
> Installation of Swiftlint & Swiftgen added

- CHANGELOG.md
> Add Changelog for 0.0.1-15

- secant.xcodeproj/project.pbxproj
- secant/Features/BackupFlow/Views/RecoveryPhraseBackupValidationView.swift
- secant/Features/BackupFlow/Views/RecoveryPhraseDisplayView.swift
- secant/Features/BackupFlow/Views/ValidationFailedView.swift
- secant/Features/BackupFlow/Views/ValidationSucceededView.swift
- secant/Features/Onboarding/OnboardingStore.swift
- secant/Features/Onboarding/Views/Onboarding.swift
- secant/Features/Welcome/WelcomeView.swift
- secant/Localizable.strings
- secant/Screens/Onboarding/OnboardingFooterView.swift
Issue #174 
All screens' strings that are meaningful for the demo application have been moved to the strings file.
> Required strings localized

- secant/Features/BackupFlow/Views/ValidationFailedView.swift
> Hotfix for the broken animation

- secant/Colors.xcassets/BackgroundColors/red.colorset/Contents.json
- secant/Colors.xcassets/ScreenBackground/greenGradientEnd.colorset/Contents.json
- secant/Colors.xcassets/ScreenBackground/greenGradientStart.colorset/Contents.json
- secant/Colors.xcassets/ScreenBackground/redGradientEnd.colorset/Contents.json
- secant/Colors.xcassets/ScreenBackground/redGradientStart.colorset/Contents.json
- secant/Features/BackupFlow/Views/ValidationFailedView.swift
- secant/Features/BackupFlow/Views/ValidationSucceededView.swift
- secant/Localizable.strings
- secant/UIComponents/Backgrounds/ScreenBackground.swift
- secant/UIComponents/CircularFrame/CircularFrameBadge.swift
> Validation Failure/Success updated to handle dark mode

- CHANGELOG.md
> Issue #172: build 0.0.1-16

- secant.xcodeproj/project.pbxproj
- secant/Util/UserPreferencesStorage.swift
- secantTests/Util/UserPreferencesStorageTests.swift
Issue #196 
Initial user preferences storage
> User preferences storage

- secant/Features/App/App.swift
- secant/Features/App/Views/AppView.swift
- secant/SecantApp.swift
> Onboarding -> Create Wallet -> Backup Phrase flows connected

- secant.xcodeproj/project.pbxproj
- secant/Features/App/App.swift
- secant/Features/App/Views/AppView.swift
- secant/Features/Welcome/Welcome.swift
- secant/Features/Welcome/WelcomeView.swift
debug menus are accessible starting on welcome screen and following 2 steps in a sequence:
1. long press (wait 0.75s+)
2. swipe up/down to access either home/startup
This work also fixed user's got stuck when running the app
> Hidden gestures to access debug menus added

- secant.xcodeproj/project.pbxproj
- secant/Features/App/App.swift
- secant/Util/DatabaseFiles.swift
- secant/Wrappers/WrappedFileManager.swift
- secantTests/Util/DatabaseFilesTests.swift
> database files dependency finished

- secant/Features/App/App.swift
- secant/Features/App/Views/AppView.swift
Also the unhandled states implemented. I was (manual) testing the flow and killed the app at certain moment and figured out there are some cases unhandled - mostly related the backup test and if user have finished it or still haven't.
IMPORTANT: the next task is to provide tests to cover the whole flow ([issue 222](https://github.com/zcash/secant-ios-wallet/issues/222))
Closes #242 
> Debug nuke wallet implemented

- secant/Features/BackupFlow/RecoveryPhraseValidation.swift
> Missing chips order randomized

- secant/Features/App/App.swift
- secant/Features/App/Views/AppView.swift
- secant/Features/ImportWallet/ImportWalletStore.swift
- secant/Features/ImportWallet/Views/ImportWalletView.swift
- secant/Features/Onboarding/OnboardingStore.swift
- secant/Features/Onboarding/Views/Onboarding.swift
- secant/Screens/Onboarding/OnboardingContentView.swift
- secant/Screens/Onboarding/OnboardingFooterView.swift
- secant/Screens/Onboarding/OnboardingHeaderView.swift
- secant/Screens/Onboarding/OnboardingScreen.swift
- secantTests/OnboardingTests/OnboardingStoreTests.swift
> Check and store of the imported wallet

- secant.xcodeproj/project.pbxproj
- secant/Util/WalletStorage.swift
- secant/Util/WalletStorageInteractor.swift
- secant/Wrappers/WrappedSecItem.swift
- secantTests/Util/WalletStorageTests.swift
- secantTests/Util/WrappedSecItemTests.swift
> Wrapped Security and Keychain handling

- secant.xcodeproj/project.pbxproj
- secant/Features/App/App.swift
- secantTests/AppReducer/AppReducerTests.swift
> Initialization refactored & covered by tests

- secant/Features/App/App.swift
- secantTests/AppReducer/AppReducerTests.swift
> Fix for the app start critical bug

- secant/Colors.xcassets/Shadow/numberedTextShadow.colorset/Contents.json
- secant/Colors.xcassets/Text/Button.colorset/Contents.json
> Chips colors fixed

- secant.xcodeproj/project.pbxproj
- secant/Features/App/App.swift
- secant/Features/App/Views/AppView.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Home/Views/HomeView.swift
- secant/Features/Sandbox/SandboxStore.swift
- secant/Features/Sandbox/Views/SandboxView.swift
- secant/Features/Welcome/Welcome.swift
- secant/Features/Welcome/WelcomeView.swift
Closes #266 
This work is neccessary for the issue 255 [Scaffold] Home Screen. The previous navigation placeholder proof work was sitting under the Home name terminology and we will need it. I refactored the whole placeholder navigation, named it SandboxView and rewired some debug menus flows. 
New Home is clean and ready for the scaffolding...
> Old home->sandbox, new home for #255

- secant.xcodeproj/project.pbxproj
- secant/Colors.xcassets/Shadow/drawerShadow.colorset/Contents.json
- secant/Features/App/Views/AppView.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Home/Views/HomeView.swift
- secant/Features/TransactionHistory/Views/TransactionHistoryView.swift
- secant/Generated/XCAssets+Generated.swift
- secant/UIComponents/Drawer/Drawer.swift
> Drawer with Transactions for the Home Screen

- secant.xcodeproj/project.pbxproj
the project fails to lint because of the version pinned is too old
Closes #279 
> Issue #279 - update swiftlint

- secant/Features/Home/Views/HomeView.swift
Closes #278 
FYI, the GeometryReaded is returning 0 for the size, whatever related on it needs to be postponed some time, typically solved by DispatchAsyncAfter (for WithAnimation cases)... We need to use drawer only if the size is defined.
> Drawer animation fix

- secant/Features/Home/HomeStore.swift
- secant/Features/TransactionHistory/TransactionHistoryStore.swift
- secant/Features/TransactionHistory/Views/TransactionHistoryView.swift
> (Non)Scrollable Transactions

- secant.xcodeproj/project.pbxproj
- secant/Features/App/App.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Home/Views/HomeView.swift
- secant/Wrappers/WrappedSDKSynchronizer.swift
- secantTests/AppReducer/AppReducerTests.swift
> WrappedSynchronizer

- CONTRIBUTING.md
Using the one present on ZcashLightClientKit
Closes #295
> [#295] Update "Commit Messages" section of CONTRIBUTING.md

- secant.xcodeproj/project.pbxproj
- secant/Util/UserPreferencesStorage.swift
- secant/Wrappers/WrappedUserDefaults.swift
- secantTests/UtilTests/UserPreferencesStorageTests.swift
> User preferences TCA

- secant.xcodeproj/project.pbxproj
- secant/Features/Home/HomeStore.swift
- secant/Features/Home/Views/HomeView.swift
- secant/Features/Sandbox/Views/SandboxView.swift
- secant/Features/Send/SendStore.swift
- secant/Features/Send/Views/CreateTransactionView.swift
- secant/Features/Send/Views/SendView.swift
- secant/Features/Send/Views/TransactionConfirmationView.swift
- secant/UIComponents/TextFields/Components/TextFieldStore.swift
- secant/UIComponents/TextFields/TransactionInputStore.swift
- secant/UIComponents/TextFields/TransactionTextField.swift
- secant/Wrappers/WrappedNotificationCenter.swift
- secant/Wrappers/WrappedSDKSynchronizer.swift
- secantTests/UtilTests/UserPreferencesStorageTests.swift
> Synchronizer status on Home Screen

- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Features/BackupFlow/Views/RecoveryPhraseBackupValidationView.swift
- secant/Features/Send/Views/CreateTransactionView.swift
- secant/Screens/Onboarding/OnboardingContentView.swift
- secant/UIComponents/CircularFrame/CircularFrameBackground.swift
- secant/UIComponents/CircularFrame/CircularFrameBadge.swift
- secant/UIComponents/TextFields/Components/TextFieldStore.swift
Closes #215 
Closes #306 
This fixes a potential error when rendering because the ForEach does not have Identifiable elements to iterate with.
Also there's a compilation error that is blocking from releasing to testflight. 
> Fix warnings and compilation error on release builds

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Features/App/AppStore.swift
Closes #300
also. Update the commit hash for the sdk
> [#300] Use .live pasteboard on live views of the app.

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secantTests/AppReducerTests/AppReducerTests.swift
- secantTests/OnboardingTests/OnboardingStoreTests.swift
- secantTests/RecoveryPhraseValidationTests/RecoveryPhraseValidationTests.swift
- secantTests/SendTests/SendTests.swift
Closes #319 
- TCA updated to 0.35.0
- tests modified so no state change is reflected
> [319] Update TCA to 0.35.0

- secant/Features/App/AppStore.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/ImportWallet/ImportWalletStore.swift
- secant/Features/OnboardingFlow/OnboardingFlowStore.swift
- secant/Features/Profile/ProfileStore.swift
- secant/Features/Profile/ProfileView.swift
- secant/Features/Sandbox/SandboxStore.swift
- secant/Features/Sandbox/SandboxView.swift
- secant/Features/SendFlow/SendFlowStore.swift
- secant/Features/SendFlow/SendFlowView.swift
- secantTests/AppReducerTests/AppReducerTests.swift
- secantTests/SendTests/SendTests.swift
Closes #285 
- context based routing in Home Screen
- mnemonic refactor
- backup phrase display from the profile screen
> [285] Advanced Routing

- secant.xcodeproj/project.pbxproj
- secant/Dependencies/URIParser.swift
- secant/Features/App/AppStore.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayStore.swift
- secant/Features/RecoveryPhraseValidationFlow/RecoveryPhraseValidationFlowStore.swift
- secant/Features/Scan/ScanStore.swift
- secant/Features/Scan/ScanView.swift
- secant/Features/Scan/UIKitBridge/QRCodeScanView.swift
- secant/Features/Scan/UIKitBridge/ScanUIView.swift
- secant/Features/TransactionHistoryFlow/TransactionHistoryFlowStore.swift
- secant/Info.plist
- secant/Resources/Colors.xcassets/QRScan/Contents.json
- secant/Resources/Colors.xcassets/QRScan/frame.colorset/Contents.json
- secant/Resources/Colors.xcassets/Text/highlightedSuperscriptText.colorset/Contents.json
- secant/Resources/Generated/XCAssets+Generated.swift
- secant/UI Components/Chips/EnumeratedChip.swift
- secant/Wrappers/WrappedAudioServices.swift
- secant/Wrappers/WrappedCaptureDevice.swift
- secant/Wrappers/WrappedURIParser.swift
- secantTests/AppReducerTests/AppReducerTests.swift
- secantTests/RecoveryPhraseValidationTests/RecoveryPhraseValidationTests.swift
- secantTests/ScanTests/ScanTests.swift
> [#106] [Scaffold] Scan QR Screen

- secant.xcodeproj/project.pbxproj
- secant/SecantApp.swift
- secant/Utils/Double+Zcash.swift
- secant/Utils/Int64+Zcash.swift
- secant/Utils/Strings.swift
- secant/Utils/Zatoshi.swift
- secantTests/UtilTests/ZatoshiTests.swift
Closes #272 
- Zatoshi type implemented
- ZEC type implemented with set of math operators
- conversions implemented
- unit tests for all kinds of operations with the Zatoshi and ZEC
> [272] Decimals and Zatoshi type

- secant.xcodeproj/project.pbxproj
- secant/Wrappers/WrappedSDKSynchronizer.swift
- secantTests/AppTests/AppTests.swift
- secantTests/HomeTests/HomeTests.swift
Closes #323 
- integration test for the .onAppear action
- unit tests for the synchronizer status change
- unit tests for the drawer and tracsation history
> [323] Unit/Integration tests for Home

- secant.xcodeproj/project.pbxproj
- secant/Features/Home/HomeStore.swift
- secant/Features/Sandbox/SandboxView.swift
- secant/Features/SendFlow/SendFlowStore.swift
- secant/Features/SendFlow/SendFlowView.swift
- secant/Features/Settings/SettingsStore.swift
- secant/Features/WalletInfo/WalletInfoStore.swift
- secant/UI Components/TextFields/TCATextField/TCATextFieldStore.swift
- secant/UI Components/TextFields/TransactionAmount/TransactionAmountTextField.swift
- secant/UI Components/TextFields/TransactionAmount/TransactionAmountTextFieldStore.swift
- secant/Utils/Strings.swift
- secant/Wrappers/WrappedNumberFormatter.swift
- secantTests/SendTests/SendTests.swift
- secantTests/SendTests/TransactionAmountInputTests.swift
- secantTests/UtilTests/ZatoshiTests.swift
Closes #312 
- WrappedNumberFormatter implemented
- unit tests updated to inject en_US locale
- cleaned up all XCTSkipUnless
> [312] WrappedNumberFormatter

- CHANGELOG.md
- secant.xcodeproj/project.pbxproj
> Build 0.0.1-27 + changelog

- secant.xcodeproj/project.pbxproj
- secantTests/SnapshotTests/RecoveryPhraseDisplaySnapshotTests/RecoveryPhraseDisplaySnapshotTests.swift
> [341] Take Phrase Display Snapshots

- secant.xcodeproj/project.pbxproj
- secantTests/SnapshotTests/RecoveryPhraseValidationFlowSnapshotTests/RecoveryPhraseValidationFlowSnapshotTests.swift
Closes #342 
Closes #343 
Closes #344 
- the backup is the whole flow so the implementation covers all screens:
- preamble
- validation with 4 steps to fill in the chips
- success/failure screens
> [342] Take empty validation puzzle snapshot

- secant.xcodeproj/project.pbxproj
- secant/Features/Home/HomeStore.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeSnapshotTests.swift
Closes #346 
- home snapshot with mocked data
- also in the full history view
> [346] Take Synced home screen snapshot

- secant/Features/RecoveryPhraseValidationFlow/RecoveryPhraseValidationFlowStore.swift
- secant/Wrappers/WrappedFeedbackGenerator.swift
Closes #324 
- specific feedback calls for the feedback generator
> [324] WrappedFeedbackGenerator refactor

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [358] Xcode project broken

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #375 
- updated
- build works
- tests work
> [375] Update ComposableArchitecure to 0.37.0

- secant.xcodeproj/project.pbxproj
- secant/Features/App/AppStore.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Sandbox/SandboxStore.swift
- secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift
- secant/Features/WalletEventsFlow/WalletEventsFlowStore.swift
- secant/Features/WalletEventsFlow/WalletEventsFlowView.swift
- secant/Models/TransactionState.swift
- secant/Models/WalletEvent.swift
- secant/Resources/Colors.xcassets/Text/TransactionDetailText.colorset/Contents.json
- secant/Resources/Generated/XCAssets+Generated.swift
- secant/Wrappers/WrappedSDKSynchronizer.swift
- secantTests/AppTests/AppTests.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/SendTests/SendTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeSnapshotTests.swift
- secantTests/SnapshotTests/WalletEventsSnapshotTests/WalletEventsSnapshotTests.swift
- secantTests/WalletEventsTests/WalletEventsTests.swift
Closes #96 
- the view holding all requested (mocked) data is prepared
- copy to pasteboard implemented
- deeplink 'reply-to' memo implemented
- view online implemented and button visible only when the URL is valid
- asset color for the texts
- unit tests
- snapshot tests
> [96] [Scaffold] Received Transaction Details

- secant/Dependencies/ZCashSDKEnvironment.swift
- secant/Features/App/AppStore.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Sandbox/SandboxStore.swift
- secant/Features/SendFlow/SendFlowStore.swift
- secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift
- secant/Features/WalletEventsFlow/WalletEventsFlowStore.swift
- secant/Models/TransactionState.swift
- secant/Models/WalletEvent.swift
- secant/Resources/Colors.xcassets/BackgroundColors/red.colorset/Contents.json
- secant/Resources/Colors.xcassets/ScreenBackground/greenGradientStart.colorset/Contents.json
- secant/Resources/Colors.xcassets/TransactionDetail/Contents.json
- secant/Resources/Colors.xcassets/TransactionDetail/FailedMark.colorset/Contents.json
- secant/Resources/Colors.xcassets/TransactionDetail/HighlightMark.colorset/Contents.json
- secant/Resources/Colors.xcassets/TransactionDetail/InactiveMark.colorset/Contents.json
- secant/Resources/Colors.xcassets/TransactionDetail/NeutralMark.colorset/Contents.json
- secant/Resources/Colors.xcassets/TransactionDetail/SucceededMark.colorset/Contents.json
- secant/Resources/Generated/XCAssets+Generated.swift
- secant/Wrappers/WrappedSDKSynchronizer.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/SendTests/SendTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeSnapshotTests.swift
- secantTests/SnapshotTests/WalletEventsSnapshotTests/WalletEventsSnapshotTests.swift
- secantTests/WalletEventsTests/WalletEventsTests.swift
Closes #362 
Closes #363 
- transaction detail has been cut into pieces that can be composed to various versions of the detail
- handling all 4 cases (sent, received, pending, failed)
- confirmations counting
- pending transaction status fixed
- tests fixed
- failed transactions
> [362] [scaffold] Pending Transaction Details

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secantTests/WalletEventsTests/WalletEventsTests.swift
Closes #384
- TCA updated
- tests fixed
> [384] Update to ComposableArchitecture 0.38.2

- secant.xcodeproj/project.pbxproj
- secant/Dependencies/AppVersionHandler.swift
- secant/Dependencies/ZCashSDKEnvironment.swift
- secant/Features/AddressDetails/AddressDetailsStore.swift
- secant/Features/AddressDetails/AddressDetailsView.swift
- secant/Features/App/AppView.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Profile/ProfileStore.swift
- secant/Features/Profile/ProfileView.swift
- secant/Features/SendFlow/SendFlowView.swift
- secant/Resources/Colors.xcassets/Text/moreInfoText.colorset/Contents.json
- secant/Resources/Generated/XCAssets+Generated.swift
- secant/Utils/QRCodeGenerator.swift
- secant/Wrappers/WrappedSDKSynchronizer.swift
- secantTests/ProfileTests/ProfileTests.swift
- secantTests/SnapshotTests/ProfileSnapshotTests/ProfileSnapshotTests.swift
Closes #73 
- qr code generator
- address details view placeholder
- navigation to address details view
- custom back
- app build + version from environment
- unit tests
- snapshot of the profile view
> [73] [Scaffold] Profile Screen

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Dependencies/LocalAuthenticationHandler.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Profile/ProfileStore.swift
- secant/Features/Profile/ProfileView.swift
- secant/Features/Sandbox/SandboxStore.swift
- secant/Features/Sandbox/SandboxView.swift
- secant/Features/SendFlow/SendFlowStore.swift
- secant/Features/Settings/SettingsStore.swift
- secant/Features/Settings/SettingsView.swift
- secant/Info.plist
- secant/Wrappers/WrappedSDKSynchronizer.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/ProfileTests/ProfileTests.swift
- secantTests/SettingsTests/SettingsTests.swift
- secantTests/SnapshotTests/ProfileSnapshotTests/ProfileSnapshotTests.swift
- secantTests/SnapshotTests/SettingsSnapshotTests/SettingsSnapshotTests.swift
Closes #75 
NOTE: The rescan might not be fully done considered UX (it flickers to home, shows synchronizer stopped and then it restarts the downloading and scanning the blocks... ) but I think it is fine as this ticket is a [Scafold] one.
- rescan blockchain feature
- backup phrase feature
- system (biometrics) authentication dependency implemented
- unit tests
- snapshot tests
- rescan cleanup
- quick and full rescan reset to home screen unit tests
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review …
> [75] [Scaffold] Settings Screen

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Dependencies/ZCashSDKEnvironment.swift
- secant/Features/App/AppStore.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Sandbox/SandboxView.swift
- secant/Features/SendFlow/SendFlowStore.swift
- secant/Features/SendFlow/SendFlowView.swift
- secant/Features/SendFlow/Views/CreateTransactionView.swift
- secant/Features/SendFlow/Views/TransactionSentView.swift
- secant/Resources/Colors.xcassets/Text/InvalidEntry.colorset/Contents.json
- secant/Resources/Colors.xcassets/TextField/MultilineOutline.colorset/Contents.json
- secant/Resources/Generated/XCAssets+Generated.swift
- secant/UI Components/TextFields/MultiLineTextField/MultiLineTextFieldStore.swift
- secant/UI Components/TextFields/MultiLineTextField/MultipleLineTextField.swift
- secantTests/DeeplinkTests/DeeplinkTests.swift
- secantTests/MultiLineTextFieldTests/MultiLineTextFieldTests.swift
- secantTests/SendTests/SendTests.swift
Closes #146 
- MultiLineTextField Store & View implemented
- memo char limit is set from the zcash sdk environment
- fixed tests
- unit tests for the multiline textfield
> [146] [UI Component] multiple line textfield

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Features/App/AppView.swift
- secant/Features/OnboardingFlow/Views/OnboardingFooterView.swift
- secant/Features/OnboardingFlow/Views/OnboardingHeaderView.swift
Closes #404 
- library updated
- all `Failed to produce diagnostics for expression` fixed
> [404] Update to ComposableArchitecture 0.39.0

- secant/Dependencies/UserPreferencesStorage.swift
- secant/Features/App/AppStore.swift
- secant/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayStore.swift
- secant/Features/RecoveryPhraseValidationFlow/RecoveryPhraseValidationFlowStore.swift
- secant/Wrappers/WrappedUserDefaults.swift
- secantTests/BackupFlowTests/RecoveryPhraseDisplayReducerTests.swift
- secantTests/DeeplinkTests/DeeplinkTests.swift
- secantTests/RecoveryPhraseValidationTests/RecoveryPhraseValidationTests.swift
- secantTests/UtilTests/UserPreferencesStorageTests.swift
Closes #408 
Following dependencies refactored to await/async
- RecoveryPhraseValidationFlowReducer
- RecoveryPhraseDisplayStore
- AppStore
- UserPreferencesStorage
- WrappedUserDefaults
which allowed to reduce imports of Combine/TCA
> [408] Reduce dependency on TCA in the dependencies

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Dependencies/ZCashSDKEnvironment.swift
- secant/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- secant/Features/BalanceBreakdown/BalanceBreakdownView.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Home/HomeView.swift
- secant/Features/SendFlow/SendFlowStore.swift
- secant/Features/SendFlow/Views/CreateTransactionView.swift
- secant/Resources/Colors.xcassets/ScreenBackground/gradientStart.colorset/Contents.json
- secant/Resources/Colors.xcassets/ScreenBackground/modalDialog.colorset/Contents.json
- secant/Resources/Colors.xcassets/ScreenBackground/semiTransparentGradientEnd.colorset/Contents.json
- secant/Resources/Colors.xcassets/ScreenBackground/semiTransparentGradientStart.colorset/Contents.json
- secant/Resources/Generated/XCAssets+Generated.swift
- secant/UI Components/Backgrounds/ScreenBackground.swift
- secant/Utils/ClearBackgroundView.swift
- secant/Wrappers/WrappedNumberFormatter.swift
- secant/Wrappers/WrappedSDKSynchronizer.swift
- secantTests/BalanceBreakdownTests/BalanceBreakdownTests.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/ProfileTests/ProfileTests.swift
- secantTests/SendTests/SendTests.swift
- secantTests/SnapshotTests/BalanceBreakdownSnapshotTests/BalanceBreakdownSnapshotTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeCircularProgressSnapshotTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeSnapshotTests.swift
- secantTests/SnapshotTests/WalletEventsSnapshotTests/WalletEventsSnapshotTests.swift
Closes #224 
- full screen cover for the balance breakdown
- clearing out the background so we can do semi transparency
- bindings for the full screen cover
- latest block business logic
- mocked auto shielding threshold
- unit tests
- snapshot tests
> [224] [Scaffold] Balance Breakdown

- secant/Dependencies/LocalAuthenticationHandler.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Profile/ProfileStore.swift
- secant/Features/Settings/SettingsStore.swift
- secantTests/ProfileTests/ProfileTests.swift
- secantTests/SettingsTests/SettingsTests.swift
- secantTests/SnapshotTests/ProfileSnapshotTests/ProfileSnapshotTests.swift
- secantTests/SnapshotTests/SettingsSnapshotTests/SettingsSnapshotTests.swift
Closes #409 
- refactored to async/await TCA
- reduced a few dependencies
- removed schedulers
- simplified the code
- cleaned up the tests
> [409] Rewrite LocalAuthenticationHandler so it supports new concurrency

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Features/App/AppStore.swift
- secant/Features/Scan/ScanStore.swift
- secant/UI Components/TextFields/TransactionAmount/TransactionAmountTextFieldStore.swift
Closes #415 
- I updated TCA library to version 0.40.2. Ticket required version 0.40.0. But in changelog I can find two minor versions containing bugfixes. It makes sense to have these in the app. 
- Update of TCA required update of combine-schedulers library from 0.7.0 to 0.8.0. combine-schedulers imported Foundation automatically with itself until version 0.7.3. This doesn't happen in newer versions. So I had to add few imports to be able to compile the secant app.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review …
> [#415] Update TCA library to version 0.40.2

- secant/SecantApp.swift
Closes #50
Before this change user was able to use 3rd party keyboard. Check the "Gboard" option on this screenshot.
And after this change 3rd party keyboards aren't available.
> [#50] Disable third party keyboards

- secant/Features/Sandbox/SandboxView.swift
- secant/Features/SendFlow/SendFlowStore.swift
Closes #432 
- obsolete bindings removed
- clear send form when the transaction is finished
- fixed broken navigation
> [#432] Navigation is broken for 2nd+ sending flow

- secant.xcodeproj/project.pbxproj
- secant/Dependencies/FeedbackGenerator.swift
- secant/Dependencies/RecoveryPhraseRandomizer.swift
- secant/Features/App/AppStore.swift
- secant/Features/RecoveryPhraseValidationFlow/RecoveryPhraseValidationFlowStore.swift
- secant/Features/RecoveryPhraseValidationFlow/Views/RecoveryPhraseBackupView.swift
- secant/Models/DropDelegate.swift
- secant/Wrappers/WrappedRecoveryPhraseRandomizer.swift
- secantTests/AppTests/AppInitializationTests.swift
- secantTests/RecoveryPhraseValidationTests/RecoveryPhraseValidationTests.swift
- secantTests/SnapshotTests/RecoveryPhraseValidationFlowSnapshotTests/RecoveryPhraseValidationFlowSnapshotTests.swift
Closes #445 
- RecoveryPhraseValidationFlow migrated to the ReducerProtocol
> [#445] Migrate RecoveryPhraseValidationFlowStore to ReducerProtocol

- secant.xcodeproj/project.pbxproj
- secant/Dependencies/MnemonicKey.swift
- secant/Dependencies/RecoveryPhraseRandomizer.swift
- secant/Dependencies/WalletStorageKey.swift
- secant/Dependencies/ZCashSDKEnvironment.swift
- secant/Features/ImportWallet/ImportWalletStore.swift
- secant/Features/OnboardingFlow/OnboardingFlowStore.swift
- secantTests/ImportWalletTests/ImportWalletTests.swift
- secantTests/SnapshotTests/ImportWalletSnapshotTests/ImportWalletSnapshotTests.swift
Closes #448 
- ImportWallet migrated
- syntax cleanup
> [#448] Migrate ImportWallet to ReducerProtocol

- secant.xcodeproj/project.pbxproj
- secant/Dependencies/FeedbackGeneratorKey.swift
- secant/Dependencies/NewRecoveryPhraseKey.swift
- secant/Dependencies/NumberFormatterKey.swift
- secant/Dependencies/PasteboardKey.swift
- secant/Dependencies/SDKSynchronizerKey.swift
- secant/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- secant/Features/BalanceBreakdown/BalanceBreakdownView.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Home/HomeView.swift
- secant/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayStore.swift
- secantTests/BalanceBreakdownTests/BalanceBreakdownTests.swift
- secantTests/SnapshotTests/BalanceBreakdownSnapshotTests/BalanceBreakdownSnapshotTests.swift
Closes #447 
- BalanceBreakdown migrated
- some terminology cleanup beyond scope of this task, the dependencies are keys essentially so I refactored all of them to follow the same syntax
> [#447] Migrate BalanceBreakdown to ReducerProtocol

- secant.xcodeproj/project.pbxproj
- secant/Dependencies/CaptureDeviceKey.swift
- secant/Dependencies/RecoveryPhraseRandomizer.swift
- secant/Dependencies/URIParser.swift
- secant/Features/App/AppStore.swift
- secant/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/ImportWallet/ImportWalletStore.swift
- secant/Features/OnboardingFlow/OnboardingFlowStore.swift
- secant/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayStore.swift
- secant/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayView.swift
- secant/Features/RecoveryPhraseValidationFlow/RecoveryPhraseValidationFlowStore.swift
- secant/Features/RecoveryPhraseValidationFlow/Views/RecoveryPhraseBackupView.swift
- secant/Features/Scan/ScanStore.swift
- secant/Features/Settings/SettingsStore.swift
- secant/Models/DropDelegate.swift
- secant/Wrappers/WrappedRecoveryPhraseRandomizer.swift
- secantTests/AppTests/AppInitializationTests.swift
- secantTests/BackupFlowTests/RecoveryPhraseDisplayReducerTests.swift
- secantTests/BalanceBreakdownTests/BalanceBreakdownTests.swift
- secantTests/ImportWalletTests/ImportWalletTests.swift
- secantTests/RecoveryPhraseValidationTests/RecoveryPhraseValidationTests.swift
- secantTests/ScanTests/ScanTests.swift
- secantTests/SettingsTests/SettingsTests.swift
- secantTests/SnapshotTests/BalanceBreakdownSnapshotTests/BalanceBreakdownSnapshotTests.swift
- secantTests/SnapshotTests/ImportWalletSnapshotTests/ImportWalletSnapshotTests.swift
- secantTests/SnapshotTests/RecoveryPhraseDisplaySnapshotTests/RecoveryPhraseDisplaySnapshotTests.swift
- secantTests/SnapshotTests/RecoveryPhraseValidationFlowSnapshotTests/RecoveryPhraseValidationFlowSnapshotTests.swift
Closes #449 
- Scan migrated to ReducerProtocol
> [#449] Migrate Scan to ReducerProtocol

- secant/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/ImportWallet/ImportWalletStore.swift
- secant/Features/RecoveryPhraseValidationFlow/RecoveryPhraseValidationFlowStore.swift
- secant/Features/Sandbox/SandboxStore.swift
- secant/Features/WalletEventsFlow/WalletEventsFlowStore.swift
- secantTests/SnapshotTests/WalletEventsSnapshotTests/WalletEventsSnapshotTests.swift
- secantTests/WalletEventsTests/WalletEventsTests.swift
Closes #450 
- WalletEvents migrated to ReducerProtocol
- some code cleanup, refactor and re-ordered
> [#450] Migrate WalletEvents to ReducerProtocol

- secant/Features/App/AppStore.swift
- secant/Features/Welcome/WelcomeStore.swift
- secantTests/SnapshotTests/WelcomeSnapshotTests/WelcomeSnapshotTests.swift
Closes #451 
- Welcome migrated to ReducerProtocol
- snapshot test fixed
> [#451] Migrate Welcome to ReducerProtocol

- secant/Dependencies/LocalAuthenticationHandler.swift
- secant/Features/Profile/ProfileStore.swift
- secant/Features/Settings/SettingsStore.swift
- secantTests/SettingsTests/SettingsTests.swift
- secantTests/SnapshotTests/SettingsSnapshotTests/SettingsSnapshotTests.swift
Closes #452 
- Settings migrated to ReducerProtocol
> [#452] Migrate Settings to ReducerProtocol

- secant/UI Components/TextFields/SingleLineTextField.swift
- secant/UI Components/TextFields/TCATextField/TCATextFieldStore.swift
- secant/UI Components/TextFields/TransactionAddress/TransactionAddressTextFieldStore.swift
- secant/UI Components/TextFields/TransactionAmount/TransactionAmountTextFieldStore.swift
- secantTests/SendTests/SendTests.swift
- secantTests/SendTests/TransactionAddressInputTests.swift
- secantTests/SendTests/TransactionAmountInputTests.swift
- secantTests/SnapshotTests/SendSnapshotTests/TransactionConfirmationSnapshotTests.swift
- secantTests/SnapshotTests/SendSnapshotTests/TransactionSendingTests.swift
Closes #465 
- TCATextField migrated to ReducerProtocol
> [#465] Migrate TCATextField to ReducerProtocol

- secant/Features/AddressDetails/AddressDetailsStore.swift
- secant/Features/Profile/ProfileStore.swift
Closes #460 
- AddressDetails migrated to ReducerProtocol
> [#460] Migrate AddressDetails to ReducerProtocol

- secant.xcodeproj/project.pbxproj
- secant/Dependencies/DerivationToolKey.swift
- secant/Features/SendFlow/SendFlowStore.swift
- secant/UI Components/TextFields/TransactionAddress/TransactionAddressTextField.swift
- secant/UI Components/TextFields/TransactionAddress/TransactionAddressTextFieldStore.swift
- secantTests/SendTests/SendTests.swift
- secantTests/SendTests/TransactionAddressInputTests.swift
- secantTests/SnapshotTests/SendSnapshotTests/TransactionConfirmationSnapshotTests.swift
- secantTests/SnapshotTests/SendSnapshotTests/TransactionSendingTests.swift
Closes #466 
- TransactionAddressTextField migrated to ReducerProtocol
> [#466] Migrate TransactionAddressTextField to ReducerProtocol

- secant/UI Components/TextFields/Components/CurrencySelection/CurrencySelectionStore.swift
- secant/UI Components/TextFields/Components/CurrencySelection/CurrencySelectionView.swift
- secant/UI Components/TextFields/TransactionAmount/TransactionAmountTextFieldStore.swift
- secantTests/SendTests/CurrencySelectionTests.swift
- secantTests/SendTests/SendTests.swift
- secantTests/SendTests/TransactionAmountInputTests.swift
- secantTests/SnapshotTests/SendSnapshotTests/TransactionConfirmationSnapshotTests.swift
- secantTests/SnapshotTests/SendSnapshotTests/TransactionSendingTests.swift
Closes #468 
- CurrencySelection migrated to ReducerProtocol
> [#468] Migrate CurrencySelection to ReducerProtocol

- secant/Features/App/AppStore.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Request/RequestStore.swift
- secant/Features/Sandbox/SandboxStore.swift
- secant/Features/Sandbox/SandboxView.swift
- secant/Features/WalletInfo/WalletInfoStore.swift
Closes #472 
- Request, WalletInfo and Sandbox migrated to ReducerProtocol
> [#472] Migrate Request, WalletInfo and Sandbox to ReducerProtocol

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #481 
- updated, all works fine
> [#481] Update TCA to 0.45.0

- secant/Features/SendFlow/SendFlowStore.swift
- secant/UI Components/TextFields/MultiLineTextField/MultiLineTextFieldStore.swift
- secantTests/MultiLineTextFieldTests/MultiLineTextFieldTests.swift
- secantTests/SendTests/SendTests.swift
Closes #464 
- MultilineTextField migrated to ReducerProtocol
> [#464] Migrate MultilineTextField to ReducerProtocol

- secant/Dependencies/AppVersionHandler.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Profile/ProfileStore.swift
- secant/Features/Profile/ProfileView.swift
- secant/Features/Sandbox/SandboxStore.swift
- secantTests/ProfileTests/ProfileTests.swift
- secantTests/SnapshotTests/ProfileSnapshotTests/ProfileSnapshotTests.swift
Closes #462 
- Profile migrated to ReducerProtocol
- sandbox feature still works with all the TCA pullback/scope navigation
> [#462] Migrate Profile to ReducerProtocol

- secant/Features/App/AppStore.swift
- secant/Features/OnboardingFlow/OnboardingFlowStore.swift
- secant/Features/OnboardingFlow/OnboardingFlowView.swift
- secant/Features/OnboardingFlow/Views/OnboardingContentView.swift
- secant/Features/OnboardingFlow/Views/OnboardingFooterView.swift
- secant/Features/OnboardingFlow/Views/OnboardingHeaderView.swift
- secantTests/OnboardingTests/OnboardingStoreTests.swift
- secantTests/SnapshotTests/OnboardingSnapshotTests/OnboardingSnapshotTests.swift
Closes #461 
- OnboardingFlow migrated to ReducerProtocol
> [#461] Migrate OnboardingFlow to ReducerProtocol

- secant/Dependencies/DiskSpaceChecker.swift
- secant/Features/App/AppStore.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Home/HomeView.swift
- secant/Wrappers/WrappedAudioServices.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeCircularProgressSnapshotTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeSnapshotTests.swift
- secantTests/SnapshotTests/WalletEventsSnapshotTests/WalletEventsSnapshotTests.swift
Closes #470 
- Home migrated to ReducerProtocol
> [#470] Migrate Home to ReducerProtocol

- secant/Dependencies/RecoveryPhraseRandomizer.swift
- secant/Features/App/AppStore.swift
- secant/Features/App/AppView.swift
- secant/Features/RecoveryPhraseValidationFlow/RecoveryPhraseValidationFlowStore.swift
- secant/Wrappers/WrappedDatabaseFiles.swift
- secant/Wrappers/WrappedDeeplinkHandler.swift
- secantTests/AppTests/AppInitializationTests.swift
- secantTests/AppTests/AppTests.swift
- secantTests/DeeplinkTests/DeeplinkTests.swift
- secantTests/HomeTests/HomeTests.swift
Closes #469 
- AppStore migrated to ReducerProtocol
> [#469] Migrate AppStore to ReducerProtocol

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Features/App/AppStore.swift
- secantTests/AppTests/AppInitializationTests.swift
- secantTests/AppTests/AppTests.swift
- secantTests/BackupFlowTests/RecoveryPhraseDisplayReducerTests.swift
- secantTests/DeeplinkTests/DeeplinkTests.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/ImportWalletTests/ImportWalletTests.swift
- secantTests/ProfileTests/ProfileTests.swift
- secantTests/RecoveryPhraseValidationTests/RecoveryPhraseValidationTests.swift
- secantTests/ScanTests/ScanTests.swift
- secantTests/SendTests/SendTests.swift
- secantTests/SendTests/TransactionAmountInputTests.swift
- secantTests/SettingsTests/SettingsTests.swift
- secantTests/WalletEventsTests/WalletEventsTests.swift
Closes #492 
- library updated
- overrides for the dependencies are now done in the trailing closures
- some tests were split to so they cover only 1 case (not 2 cases in one test)
> [#492] Update TCA to 0.46.0

- secant.xcodeproj/project.pbxproj
- secant/Features/Root/RootStore.swift
- secant/Features/Root/RootView.swift
- secant/SecantApp.swift
- secantTests/AppTests/AppInitializationTests.swift
- secantTests/AppTests/AppTests.swift
- secantTests/DeeplinkTests/DeeplinkTests.swift
Closes #495 
- app->root refactor for all instances of prefixes (store, reducer, viewStore, files and folders)
> [#495] Rename AppStore to avoid conceptual confusions

- secant/Features/OnboardingFlow/OnboardingFlowView.swift
- secant/Features/OnboardingFlow/Views/OnboardingContentView.swift
- secant/Features/OnboardingFlow/Views/OnboardingFooterView.swift
- secant/Features/OnboardingFlow/Views/OnboardingHeaderView.swift
- secant/UI Components/FontStyles/SecantTextStyles.swift
Closes #179 
- reimagined the way the onboarding is composed
- the bare bone is now a VStack instead of a ZStack
- there is no use of GeometryReader anymore
- the new solution works fine with the accessibilityLarge
> [#179] Broken Onboarding UI for .accessibilityLarge

- secant/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayView.swift
- secant/Features/Root/RootInitialization.swift
- secant/Features/Settings/SettingsStore.swift
- secant/UI Components/DesignGuide.swift
- secant/Utils/Previews.swift
- secant/Utils/Strings.swift
> [#512] Check that every TODO in code has an open issue

- secant.xcodeproj/project.pbxproj
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerInterface.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerMocks.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerTest.swift
- secant/Features/AddressDetails/AddressDetailsStore.swift
- secant/Features/AddressDetails/AddressDetailsView.swift
- secant/Features/Profile/ProfileStore.swift
- secant/Features/Profile/ProfileView.swift
- secantTests/AddressDetailsTests/AddressDetailsTests.swift
- secantTests/ProfileTests/ProfileTests.swift
- secantTests/SnapshotTests/AddressDetailsSnapshotTests/AddressDetailsSnapshotTests.swift
Closes #514 
- UAs integrated to the Profile and Address details screen
- Snapshot tests for the AddressDetailsView
- Unit tests for the AddressDetailsStore
> [#514] Adopt Unified Addresses

- secant/Features/AddressDetails/AddressDetailsView.swift
- secant/Features/Profile/ProfileView.swift
- secant/Features/SendFlow/SendFlowStore.swift
- secant/Features/SendFlow/SendFlowView.swift
- secant/UI Components/TextFields/TransactionAddress/TransactionAddressTextField.swift
- secant/UI Components/TextFields/TransactionAddress/TransactionAddressTextFieldStore.swift
- secantTests/SendTests/SendTests.swift
Closes #517 
- Address details have been extended to show QR codes for the addresses
- Profile + Address views are now scroll views
- Send feature now supports scan QR feature, when valid zcash address is scanned the address is automatically filled
- snapshot tests & unit tests fixed and extended accordingly
> [#517] QR codes integration into the wallet details and send feature

- .swiftlint.yml
- secant/Dependencies/Deeplink/Deeplink.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerMocks.swift
- secant/Dependencies/WalletStorage/WalletStorage.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/ImportWallet/ImportWalletStore.swift
- secant/Features/OnboardingFlow/Views/OnboardingContentView.swift
- secant/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayStore.swift
- secant/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayView.swift
- secant/Features/Root/RootDestination.swift
- secant/Features/Root/RootInitialization.swift
- secant/Features/Root/RootStore.swift
- secant/Features/Scan/ScanStore.swift
- secant/Features/Settings/SettingsStore.swift
- secant/Features/WalletEventsFlow/Views/TransactionRowView.swift
- secant/Models/WalletEvent.swift
- secant/UI Components/DesignGuide.swift
- secant/UI Components/TextFields/Components/CurrencySelection/CurrencySelectionStore.swift
- secant/UI Components/TextFields/TransactionAmount/TransactionAmountTextFieldStore.swift
- secant/Utils/DebugMenu.swift
- secant/Utils/Previews.swift
- secant/Utils/Strings.swift
- secantTests/UtilTests/WalletStorageTests.swift
- TODO rule updated in the yml file
- all TODOs updated to the new format
- some missing TODOs updated as well
- code cleanup
> [#521] Update format for the Swiftlint TODO rule

- secant.xcodeproj/project.pbxproj
- deployment target set to iOS 15
- no warnings or errors needed to be addressed
> [#520] Set iOS 15 as minimum deployment target

- .swiftlint.yml
- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Dependencies/DatabaseFiles/DatabaseFiles.swift
- secant/Dependencies/DatabaseFiles/DatabaseFilesInterface.swift
- secant/Dependencies/DatabaseFiles/DatabaseFilesLiveKey.swift
- secant/Dependencies/DatabaseFiles/DatabaseFilesTestKey.swift
- secant/Dependencies/WalletStorage/WalletStorage.swift
- secant/Dependencies/ZcashSDKEnvironment/ZcashSDKEnvironmentInterface.swift
- secant/Dependencies/ZcashSDKEnvironment/ZcashSDKEnvironmentLiveKey.swift
- secant/Dependencies/ZcashSDKEnvironment/ZcashSDKEnvironmentTestKey.swift
- secant/Features/ImportWallet/ImportWalletStore.swift
- secant/Features/Root/RootInitialization.swift
- secant/Features/Root/RootStore.swift
- secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift
- secant/Features/WalletEventsFlow/Views/TransactionRowView.swift
- secant/Features/WalletEventsFlow/WalletEventsFlowView.swift
- secant/UI Components/Shapes/Wedge.swift
- secant/Utils/Bindings.swift
- secantTests/ImportWalletTests/ImportWalletTests.swift
- secantTests/ProfileTests/ProfileTests.swift
- secantTests/UtilTests/DatabaseFilesTests.swift
- secantTests/UtilTests/WalletStorageTests.swift
This adopts commit `cf60f44aa83938432c81361917406483ff42c719` from `main` branch of ZcashLightClientKit.
It includes changes to remove a fake "defaultBirthday" and use the real `BlockHeight.ofLatestCheckpoint()` function that allows the wallets to fetch the latest checkpoint available from bundle and define it as the birthday.
removes references to `LightWalletService` since this class has been made internal to the SDK only.
adopts FsBlockDb and adds a FsBlockDbRoot directory dependency for the Databases dependencies. Which should be renamed in a later commit
Closes #541
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more …
> [#541] Adopt Latest main commit of SDK

- secant.xcodeproj/project.pbxproj
This fixes the path of the dummy google services file injected at startup of the build process.
Closes #545
> [#545] Fix CI issues with PR builds

- secant/Features/Home/HomeStore.swift
Closes #537 
- flaky navigation reproduced and fixed
> [#537] Flaky navigation issue

- secant/Dependencies/UserPreferencesStorage/UserPreferencesStorageInterface.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Home/HomeView.swift
- secant/Features/WalletEventsFlow/WalletEventsFlowStore.swift
- secant/Features/WalletEventsFlow/WalletEventsFlowView.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeCircularProgressSnapshotTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeSnapshotTests.swift
- secantTests/SnapshotTests/WalletEventsSnapshotTests/WalletEventsSnapshotTests.swift
- secantTests/WalletEventsTests/WalletEventsTests.swift
Closes #564 
- the transaction history is now separated
- snapshot test updated
> [#564] Add transaction history as standalone screen

- .swiftlint.yml
- secant.xcodeproj/project.pbxproj
- secant/Dependencies/FeatureFlagsManager/UserDefaultsWalletConfigStorage.swift
- secant/Dependencies/FeatureFlagsManager/WalletConfigProvider.swift
- secant/Dependencies/FeatureFlagsManager/WalletConfigProviderInterface.swift
- secant/Dependencies/FeatureFlagsManager/WalletConfigProviderLiveKey.swift
- secant/Dependencies/FeatureFlagsManager/WalletConfigProviderTestKey.swift
- secant/Models/WalletConfig.swift
- secantTests/WalletConfigProvider/WalletConfigProviderTests.swift
- Added `FeaturesFlagManager` object which handles loading and caching of feature flags.
- Added `FeatureFlagsConfiguration` which represents one configuration of all feature flags.
> [#554] Add WalletConfigProvider

- secant/UI Components/TextFields/TransactionAmount/TransactionAmountTextFieldStore.swift
> [#577] Fix TCA warning

- secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift
Closes #565 
- the screen is now simplified and standalone, works for sent, failed, pending and received details
> [#565] Add transaction details as standalone screen

- secant/Dependencies/WalletConfigProvider/WalletConfigProviderInterface.swift
- secant/Dependencies/WalletConfigProvider/WalletConfigProviderLiveKey.swift
- secant/Dependencies/WalletConfigProvider/WalletConfigProviderTestKey.swift
- secant/Features/Root/RootDestination.swift
- secant/Features/Root/RootInitialization.swift
- secant/Features/Root/RootStore.swift
- secant/Features/Root/RootView.swift
- secant/Models/WalletConfig.swift
- secantTests/WalletConfigProviderTests/WalletConfigProviderTests.swift
> [#554] Add ability to update feature flags from debug screen

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerInterface.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerMocks.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerTest.swift
- secant/Features/Root/RootDestination.swift
- secant/Features/Root/RootInitialization.swift
- secant/Features/Root/RootStore.swift
- secant/Features/Root/RootView.swift
- secantTests/HomeTests/HomeTests.swift
Closes #535 
This PR is a draft until SDK's #793 is done
- wipe() integration
- unit tests added and fixed
- wipe call logic enhanced to cover all 3 cases that can happen
- FIXME added
> [#535] Use 0.18.0's wipe() instead of obsolete nuke approach

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Dependencies/WalletConfigProvider/WalletConfigProvider.swift
- secant/Dependencies/WalletConfigProvider/WalletConfigProviderInterface.swift
- secant/Dependencies/WalletConfigProvider/WalletConfigProviderLiveKey.swift
- secant/Dependencies/WalletConfigProvider/WalletConfigProviderTestKey.swift
- secant/Features/Root/RootDestination.swift
- secant/Features/Root/RootInitialization.swift
- secant/Features/Root/RootStore.swift
- secantTests/RootTests/AppInitializationTests.swift
- secantTests/RootTests/RootTests.swift
- secantTests/WalletConfigProviderTests/WalletConfigProviderTests.swift
Closes #586 
Closes #584 
- Publisher used instead of .task/.run
- fixed all tests
- WalletConfigProvider converted to Combine
> [#586] secantTests.AppInitializationTests Tests fail on CI

- .swiftlint_tests.yml
- secant.xcodeproj/project.pbxproj
Closes #546
- Include swiftlint binary into repository.
- Have separate swiftlint config for code and for tests.
> [#546] Update how swiftlint is used

- secant.xcodeproj/project.pbxproj
- secant/Dependencies/SupportDataGenerator/SupportDataGenerator.swift
- secant/Dependencies/SupportDataGenerator/SupportDataGeneratorInterface.swift
- secant/Dependencies/SupportDataGenerator/SupportDataGeneratorLiveKey.swift
- secant/Dependencies/SupportDataGenerator/SupportDataGeneratorTestKey.swift
- secant/Features/Profile/ProfileView.swift
- secant/Features/Settings/SettingsStore.swift
- secant/Features/Settings/SettingsView.swift
- secant/Features/Settings/UIKitBridge/UIMailDialog.swift
- secantTests/SettingsTests/SettingsTests.swift
Closes #575
- Added `SupportDataGenerator` object which generates data sent with support email. Format of the data is based on what Android has.
- Support button is moved to settings from profile.
- Support button opens mail composer.
> [#575] Add support for sending feedback

- secant.xcodeproj/project.pbxproj
- secant/Dependencies/RecoveryPhraseRandomizer/RecoveryPhraseRandomizerInterface.swift
- secant/Dependencies/WalletStorage/WalletStorage.swift
- secant/Dependencies/WalletStorage/WalletStorageInterface.swift
- secant/Dependencies/WalletStorage/WalletStorageLiveKey.swift
- secant/Dependencies/WalletStorage/WalletStorageTestKey.swift
- secant/Features/ImportWallet/ImportWalletStore.swift
- secant/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayStore.swift
- secant/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayView.swift
- secant/Features/Root/RootDestination.swift
- secant/Features/Root/RootInitialization.swift
- secant/Models/RecoveryPhrase.swift
- secant/Models/WalletConfig.swift
- secant/Resources/Localizable.strings
- secant/UI Components/FontStyles/SecantTextStyles.swift
- secantTests/RecoveryPhraseValidationTests/RecoveryPhraseValidationFlowFeatureFlagTests.swift
- secantTests/SettingsTests/SettingsTests.swift
- secantTests/WalletConfigProviderTests/WalletConfigProviderTests.swift
Closes #556 
- flow is hidden by default
- when turned on, only new users (nuke wallet and start over) continues to the flow
- unit tests fixed and updated
- new unit tests
- phrase display screen simplified
> [#556] Hide post-seed backup flow and rework screenshot tests

- secant/Dependencies/Mnemonic/MnemonicInterface.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Home/HomeView.swift
- secant/Features/ImportWallet/ImportWalletStore.swift
- secant/Features/Root/RootDestination.swift
- secant/Features/Root/RootInitialization.swift
- secant/Features/Root/RootStore.swift
- secant/Features/Root/RootView.swift
- secant/Features/Scan/ScanStore.swift
- secant/Features/Scan/ScanView.swift
- secant/Features/Settings/SettingsStore.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/RootTests/AppInitializationTests.swift
- secantTests/RootTests/RootTests.swift
> [#576] All the errors are handled by alert

- secant/Features/Profile/ProfileView.swift
- secant/Resources/Localizable.strings
> Change "Your UA" for "Your Address"

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerInterface.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerMocks.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerTest.swift
- secant/Features/Root/RootDebug.swift
- secantTests/RootTests/DebugTests.swift
Closes #613
- Only change was in usage of rewind function. So it's changed.
- And when rewind is done then start of the sync process is called. So rewind now really works without app restart.
> [#613] Adopt ZcashLightClientKit version 0.19.0-beta

- secant.xcodeproj/project.pbxproj
- secant/Features/ImportWallet/ImportBirthdayView.swift
- secant/Features/ImportWallet/ImportWalletStore.swift
- secant/Features/ImportWallet/ImportWalletView.swift
- secantTests/SnapshotTests/ImportWalletSnapshotTests/ImportWalletSnapshotTests.swift
Closes #609 
Closes #610 
- birthday set separated from the backup seed phrase
- snapshot for the birthday screen added
> [#609] Split birthday from the import seed phrase

- secant.xcodeproj/project.pbxproj
- secant/Features/Home/HomeStore.swift
- secant/Features/Home/HomeView.swift
- secant/Features/Root/RootInitialization.swift
- secant/Models/WalletConfig.swift
- secantTests/HomeTests/HomeFeatureFlagTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeSnapshotTests.swift
- secantTests/SnapshotTests/WalletEventsSnapshotTests/WalletEventsSnapshotTests.swift
- secantTests/WalletConfigProviderTests/WalletConfigProviderTests.swift
> [#595] Visibility of fiat conversion on home page depends on feature flag

- secant.xcodeproj/project.pbxproj
- secant/Dependencies/LocalAuthentication/LocalAuthenticationLiveKey.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerMocks.swift
- secant/Dependencies/SupportDataGenerator/SupportDataGenerator.swift
- secant/Dependencies/WalletConfigProvider/UserDefaultsWalletConfigStorage.swift
- secant/Features/AddressDetails/AddressDetailsStore.swift
- secant/Features/AddressDetails/AddressDetailsView.swift
- secant/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- secant/Features/ExportLogs/ExportLogsStore.swift
- secant/Features/Home/HomeView.swift
- secant/Features/ImportWallet/ImportBirthdayView.swift
- secant/Features/ImportWallet/ImportWalletStore.swift
- secant/Features/Profile/ProfileStore.swift
- secant/Features/Root/RootDebug.swift
- secant/Features/Root/RootDestination.swift
- secant/Features/Root/RootInitialization.swift
- secant/Features/Root/RootView.swift
- secant/Features/Scan/ScanStore.swift
- secant/Features/Scan/ScanView.swift
- secant/Features/Settings/SettingsStore.swift
- secant/Features/WalletEventsFlow/WalletEventsFlowStore.swift
- secant/Models/SyncStatusSnapshot.swift
- secant/Models/WalletEvent.swift
- secant/Resources/Generated/L10n.swift
- secant/Resources/Localizable.strings
- secant/UI Components/TextFields/MultiLineTextField/MultiLineTextFieldStore.swift
- secant/UI Components/TextFields/TransactionAddress/TransactionAddressTextField.swift
- secant/UI Components/TextFields/TransactionAmount/TransactionAmountTextField.swift
Closes #617
- All the texts that weren't in the Localisable.strings file are now there.
- L10n is used for all the texts in the code.
- Fixed paths in SwiftGen build phase so L10n.swift is now correctly generated when Localisable.strings file change.
> [#617] Use L10n for all the texts in the app

- CHANGELOG.md
- secantTests/HomeTests/HomeTests.swift
> [#635] Fix HomeTests

- secant.xcodeproj/project.pbxproj
- We need to require specific version of SwiftGen because each version may generate different file. Which causes then problems with git.
- Convert build phase shell scripts to zsh.
> [#618] Require specific version of SwiftGen

- secant/Features/BalanceBreakdown/BalanceBreakdownView.swift
- secant/Features/Home/HomeView.swift
- secant/Features/SendFlow/Views/CreateTransactionView.swift
- secant/Features/SendFlow/Views/TransactionSendingView.swift
- secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift
- secant/Features/WalletEventsFlow/Views/TransactionRowView.swift
- secant/Resources/Generated/L10n.swift
- secant/Resources/Localizable.strings
- secant/SecantApp.swift
- secant/UI Components/TextFields/TransactionAmount/TransactionAmountTextField.swift
Closes #628 
- all instances of hardcoded ZEC are now dynamic depending on a target
> [#628] TAZ vs ZEC builds

- secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift
- secant/Resources/Generated/L10n.swift
- secant/Resources/Localizable.strings
> [#632] Show error message for failed transaction

- secant/Dependencies/SDKSynchronizer/SDKSynchronizerInterface.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerMocks.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerTest.swift
- secant/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- secant/Features/BalanceBreakdown/BalanceBreakdownView.swift
- secant/Resources/Generated/L10n.swift
- secant/Resources/Localizable.strings
- secantTests/BalanceBreakdownTests/BalanceBreakdownTests.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/SnapshotTests/BalanceBreakdownSnapshotTests/BalanceBreakdownSnapshotTests.swift
> [#599] Add ability to shield funds

- secant.xcodeproj/project.pbxproj
- secant/Features/SendFlow/Views/CreateTransactionView.swift
- secant/Utils/KeyboardAdaptive.swift
- secant/Utils/UIKit+Extensions.swift
- secant/Utils/UIResponder+Current.swift
Closes #631 
Closes #596 
- hiding the keyboard on tap (fix for the 596)
- adapting the layout on the keyboard appearance (fix for the 631)
> [#631] Make Send Form fields avoid being blocked by keyboard

- secant/Features/Home/HomeStore.swift
- secant/Features/Home/HomeView.swift
- secant/Features/Root/RootDebug.swift
- secant/Resources/Generated/L10n.swift
- secant/Resources/Localizable.strings
- secantTests/HomeTests/HomeTests.swift
Adds an alert showing the localized message and a button to retry to sync or to dismiss the alert with no action.
Closes #597
> [#597] Sync cannot be retried after a failure

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [#647] Adopt 0.19.1-beta

- secant/Features/SendFlow/SendFlowStore.swift
- secant/Features/SendFlow/SendFlowView.swift
- secant/Features/SendFlow/Views/CreateTransactionView.swift
- secant/Resources/Generated/L10n.swift
- secant/Resources/Localizable.strings
- secant/UI Components/TextFields/MultiLineTextField/MultipleLineTextField.swift
- secant/UI Components/TextFields/SingleLineTextField.swift
- secant/UI Components/TextFields/TransactionAddress/TransactionAddressTextField.swift
- adding/editing memo proposed to be in a sheet popover
https://user-images.githubusercontent.com/7198042/224537024-075b2426-e7eb-432c-8cd0-a31f38248068.mov
> [#650] Layout changes for the send screen

- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Features/AddressDetails/AddressDetailsView.swift
- secant/Features/Profile/ProfileView.swift
- secant/Features/Root/RootView.swift
- secant/Features/Scan/ScanView.swift
- secant/Features/SendFlow/SendFlowView.swift
- secant/Features/SendFlow/Views/CreateTransactionView.swift
- secant/UI Components/TextFields/MultiLineTextField/MultipleLineTextField.swift
- secant/UI Components/TextFields/SingleLineTextField.swift
Closes #626 
- all resolved except nav bar issue, that one will be resolved separately, [#650](https://github.com/zcash/secant-ios-wallet/issues/650)
> [#626] Small UI-UX fixes for 0.0.1-45

- secant/Features/Root/RootStore.swift
Closes #652 
- the logging infrastructure is doing exactly the same as the pointfree's  _printChanges() so there has been a duplication of logs
> [#652] Each logged TCA actions appears twice in the log

- secant.xcodeproj/project.pbxproj
- secant/Features/Settings/SettingsStore.swift
- secant/Features/Settings/SettingsView.swift
- secant/Features/Settings/Views/About.swift
- secant/Resources/Generated/L10n.swift
- secant/Resources/Localizable.strings
- secantTests/SnapshotTests/SettingsSnapshotTests/SettingsSnapshotTests.swift
Closes #658 
- about screen implemented with version only for now but place for licences, etc.
- snapshot test for the About screen added
> [#658] About Screen with version

- secant.xcodeproj/project.pbxproj
- secant/Features/BalanceBreakdown/BalanceBreakdownView.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Home/HomeView.swift
- secant/Features/ImportWallet/ImportBirthdayView.swift
- secant/Features/ImportWallet/ImportWalletView.swift
- secant/Features/SendFlow/Views/CreateTransactionView.swift
- secant/Features/Settings/SettingsView.swift
- secant/UI Components/Extensions/Button+Disabling.swift
This creates a view modifier that disables and dims the view in a single line of code
Closes #661
Also moves every button that can be disabled to use the ViewModifier
> [#661] Send Button works even if it's apparently disabled

- secant.xcodeproj/project.pbxproj
- secant/Features/Home/HomeView.swift
- secant/Features/OnboardingFlow/PlainOnboardingView.swift
- secant/Features/OnboardingFlow/Views/OnboardingFooterView.swift
- secant/Features/Root/RootView.swift
- secant/Features/SendFlow/Views/CreateTransactionView.swift
- secant/Resources/Generated/L10n.swift
- secant/Resources/Localizable.strings
- secant/UI Components/Buttons/StandardButtonStyle.swift
Also removes padding from '.activeButtonStyle' and changes padding throughout the app where it's needed
Closes #666
> [#666] Remove Graphics from "create new wallet" screen

- secant/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- secant/Features/BalanceBreakdown/BalanceBreakdownView.swift
- secantTests/BalanceBreakdownTests/BalanceBreakdownTests.swift
This adds new logic for disabling the shield funds button and tests that check that the state is consistent with the intended behaviour.
handling button opacity is left for another PR
Closes #663
> [#663] Shield Funds button is enabled when there are no funds to shield

- secant/Models/SyncStatusSnapshot.swift
- secant/Resources/Generated/L10n.swift
- secant/Resources/Localizable.strings
> Fix missing percentage on homepage while syncing

- secant/Features/BalanceBreakdown/BalanceBreakdownView.swift
- secant/Features/Home/HomeView.swift
Closes #668 
- layout & colors changed so it's not a modal semi-transparent view anymore
> [#668] Balance Breakdown design enhancements

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerInterface.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerMocks.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerTest.swift
- secant/Features/Root/RootInitialization.swift
- secant/Features/Root/RootStore.swift
Closes #653
- Just necessary changes required to adopt https://github.com/zcash/ZcashLightClientKit/pull/827
> [#653] Adopt SDK initialisation changes

- secant.xcodeproj/project.pbxproj
"SettingsView.swift:70:21: error: cannot find 'About' in scope (exit code: 1)"
Closes #676
> [#676] fix About.swift not being present on mainnet target

- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Dependencies/DerivationTool/DerivationToolLiveKey.swift
- secant/Features/SendFlow/SendFlowStore.swift
- secant/Features/SendFlow/Views/CreateTransactionView.swift
- secant/UI Components/TextFields/TransactionAddress/TransactionAddressTextFieldStore.swift
- secantTests/SendTests/SendTests.swift
Closes #673 
- memo is nil for send transaction and transparent address
- memo is hidden from the UI when transparent address is used
- derivation tool respect the network set in the target
> [#673] End to end bugfix

- secant.xcodeproj/project.pbxproj
- secant/Dependencies/CaptureDevice/CaptureDeviceInterface.swift
- secant/Dependencies/CaptureDevice/CaptureDeviceLiveKey.swift
- secant/Features/Alerts/AlertReducer.swift
- secant/Features/Alerts/AlertRequest.swift
- secant/Features/Alerts/AlertStates.swift
- secant/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- secant/Features/BalanceBreakdown/BalanceBreakdownView.swift
- secant/Features/ExportLogs/ExportLogsStore.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Home/HomeView.swift
- secant/Features/ImportWallet/ImportBirthdayView.swift
- secant/Features/ImportWallet/ImportWalletStore.swift
- secant/Features/ImportWallet/ImportWalletView.swift
- secant/Features/Root/RootDebug.swift
- secant/Features/Root/RootDestination.swift
- secant/Features/Root/RootInitialization.swift
- secant/Features/Root/RootStore.swift
- secant/Features/Root/RootView.swift
- secant/Features/Scan/ScanStore.swift
- secant/Features/Scan/ScanView.swift
- secant/Features/Settings/SettingsStore.swift
- secant/Features/Settings/SettingsView.swift
- secant/Features/WalletEventsFlow/WalletEventsFlowStore.swift
- secant/Utils/Reducers/OnChangeReducer.swift
- secantTests/BalanceBreakdownTests/BalanceBreakdownTests.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/ImportWalletTests/ImportWalletTests.swift
- secantTests/RootTests/AppInitializationTests.swift
- secantTests/RootTests/RootTests.swift
Closes #630
Closes #511
Closes #221 
- all alerts refactored and connected
> [#630] Investigate possibility to implement AlertReducer

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Dependencies/Date/DateInterface.swift
- secant/Dependencies/Date/DateLiveKey.swift
- secant/Dependencies/Date/DateTestKey.swift
- secant/Dependencies/Deeplink/Deeplink.swift
- secant/Dependencies/ReviewRequest/ReviewRequestInterface.swift
- secant/Dependencies/ReviewRequest/ReviewRequestLiveKey.swift
- secant/Dependencies/ReviewRequest/ReviewRequestTestKey.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerInterface.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerTest.swift
- secant/Features/AddressDetails/AddressDetailsStore.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Home/HomeView.swift
- secant/Features/Profile/ProfileStore.swift
- secant/Features/Root/RootDebug.swift
- secant/Features/Root/RootDestination.swift
- secant/Features/Root/RootInitialization.swift
- secant/Features/Root/RootView.swift
- secant/Features/WalletEventsFlow/WalletEventsFlowStore.swift
- secant/Resources/Generated/L10n.swift
- secant/Resources/Localizable.strings
- secantTests/AddressDetailsTests/AddressDetailsTests.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/ProfileTests/ProfileTests.swift
- secantTests/ReviewRequestTests/ReviewRequestTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeSnapshotTests.swift
- secantTests/WalletEventsTests/WalletEventsTests.swift
Closes #265 
- async adaptations of the latest sdk
- review request TCA dependency added
- set of rules for the triggering the app rating dialog
- unit tests for the review request client
- app review request logic disconnected from the production for now (based on the discussion with Nick and Pacu)
> [#265] Integrate App Rating Alert

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Dependencies/DerivationTool/DerivationToolInterface.swift
- secant/Dependencies/DerivationTool/DerivationToolLiveKey.swift
- secant/Dependencies/DerivationTool/DerivationToolTestKey.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerInterface.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerTest.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Root/RootInitialization.swift
- secant/Features/WalletEventsFlow/Views/TransactionDetailView.swift
- secant/Models/TransactionState.swift
- secant/Models/WalletEvent.swift
- secantTests/BalanceBreakdownTests/BalanceBreakdownTests.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/SendTests/SendTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeSnapshotTests.swift
- secantTests/SnapshotTests/WalletEventsSnapshotTests/WalletEventsSnapshotTests.swift
- secantTests/WalletEventsTests/WalletEventsTests.swift
Closes #705 
- synchronizer's protocol cleaned up
- latest SDK adopted
- memos back  in cleared transactions
- recipient back in cleared transactions
- pending transaction memos are back
- recieved recipients no longer available, removed from the UI
> [#705] Transaction detail lacks memo and addresses

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerInterface.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- secant/Dependencies/SDKSynchronizer/SDKSynchronizerTest.swift
- secant/Features/SendFlow/SendFlowStore.swift
- secant/Models/TransactionState.swift
- secant/Models/WalletEvent.swift
- secantTests/BalanceBreakdownTests/BalanceBreakdownTests.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/SendTests/SendTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeSnapshotTests.swift
- secantTests/SnapshotTests/WalletEventsSnapshotTests/WalletEventsSnapshotTests.swift
- secantTests/WalletEventsTests/WalletEventsTests.swift
Closes #707 
- TransactionState simplified and adopted to the latest ZcashTransaction
- WalletEvent simplified
- sendTransaction updated to the async/await
> [#707] Adopt latest SDK

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Features/Alerts/AlertRequest.swift
- secant/Features/Alerts/AlertStates.swift
- secant/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- secant/Features/ExportLogs/ExportLogsStore.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/ImportWallet/ImportWalletStore.swift
- secant/Features/Root/RootDebug.swift
- secant/Features/Root/RootDestination.swift
- secant/Features/Root/RootInitialization.swift
- secant/Features/Scan/ScanStore.swift
- secant/Features/SendFlow/SendFlowStore.swift
- secant/Features/Settings/SettingsStore.swift
- secant/Features/WalletEventsFlow/WalletEventsFlowStore.swift
- secant/Models/SyncStatusSnapshot.swift
- secant/Resources/Generated/L10n.swift
- secant/Resources/Localizable.strings
- secantTests/BalanceBreakdownTests/BalanceBreakdownTests.swift
- secantTests/DeeplinkTests/DeeplinkTests.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/ReviewRequestTests/ReviewRequestTests.swift
- secantTests/RootTests/RootTests.swift
- secantTests/SendTests/SendTests.swift
- secantTests/WalletEventsTests/WalletEventsTests.swift
Closes #709 
Closes #712 
- Strings replaced with ZcashError
- unit test don't depend on error descriptions anymore
- alerts now show error messages + code
> [#709] Better error handling in tests

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> 711 transactions not shown

- secant/Features/ImportWallet/ImportWalletStore.swift
This corrects the case for which the user does not input a birthday to restore the wallet and it needs to fall back to sapling activation Closes #717
> [#717] import birthday does not work as expected

- secant.xcodeproj/project.pbxproj
- secant/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- secant/Features/Home/HomeStore.swift
- secant/Features/Root/RootDebug.swift
- secant/Features/Root/RootInitialization.swift
- secant/Features/Root/RootStore.swift
- secant/Features/Scan/ScanStore.swift
- secant/Features/WalletEventsFlow/WalletEventsFlowStore.swift
- secantTests/SendTests/SendTests.swift
- secantTests/WalletConfigProviderTests/WalletConfigProviderTests.swift
Closes #724 
- in general, cleanup of warnings:
- unused code in the tests
- cancellable ids updated
- fulfillment instead of wait
- library updated to 0.53.0
> [#724] Adopt TCA 0.53.0

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> update ZcashLightClientKit to commit `ee3d082`

- README.md
Closes #731 
- Swiftlint section updated to 0.50.3 version
> [#731] Update Swiftlint section

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Features/Home/HomeStore.swift
- secant/Features/Root/RootView.swift
- secant/Features/SendFlow/SendFlowStore.swift
Closes #730 
- timer instead of self for CancelIDs
- TCA updated to 0.53.2
- store.score warnings fixed
> [#730] Fix warnings with TCA 0-53

- modules/.gitignore
- modules/Package.swift
- modules/Sources/modules/modules.swift
- secant.xcodeproj/project.pbxproj
Closes #735 
- project updated to hold package for future modularization
> [#735] Setup swift package

- modules/Package.swift
- modules/Sources/DateClient/DateInterface.swift
- modules/Sources/DateClient/DateLiveKey.swift
- modules/Sources/DateClient/DateTestKey.swift
- modules/Sources/modules/modules.swift
- secant.xcodeproj/project.pbxproj
- secant/Dependencies/ReviewRequest/ReviewRequestLiveKey.swift
Closes #738 
- Date dependency moved to a separate package
> [#738] Date Dependency Package

- modules/Package.swift
- modules/Sources/AppVersionClient/AppVersionInterface.swift
- modules/Sources/AppVersionClient/AppVersionLiveKey.swift
- modules/Sources/AppVersionClient/AppVersionMocks.swift
- modules/Sources/AppVersionClient/AppVersionTestKey.swift
- modules/Sources/DateClient/DateInterface.swift
- secant.xcodeproj/project.pbxproj
- secant/Dependencies/ReviewRequest/ReviewRequestLiveKey.swift
- secant/Features/Profile/ProfileStore.swift
- secant/Features/Settings/SettingsStore.swift
Closes #739 
- AppVersion dependency moved to a separate package
> [#739] AppVersion Dependency Package

- secant/SecantApp.swift
> Register custom fonts

- secant.xcodeproj/project.pbxproj
Closes #779 
- script for crashlytics symbols upload removed for now
> [#779] Release configuration not compiling

- modules/Package.swift
Closes #783 
- the version has been downgraded to 5.6 from 5.8
> [#783] Set the swift tool version to 5-6

- modules/Sources/Features/SendFlow/Views/CreateTransactionView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Colors.xcassets/MFP/error.colorset/Contents.json
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/Generated/XCAssets+Generated.swift
Closes #786 
- Send flow updated so both input field show an error
> [#786] Errors for input fields

- modules/Package.swift
- modules/Sources/Features/Home/HomeStore.swift
- modules/Sources/Features/Home/HomeView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secantTests/HomeTests/HomeTests.swift
- secantTests/ReviewRequestTests/ReviewRequestTests.swift
Closes #790 
- The SDK updated to the latest main (commit hash)
- Fixes for a few texts
- UX improvement: Upgrading databases... label for cases when it takes a few seconds, most of the times it is so quick that the label is even not visible to the user. It simple dismisses before user lands on a home page from the welcome screen
- fixed tests after adding the flag for migration
> [#790] Adopt latest SDK

- modules/Package.swift
- modules/Sources/Features/ImportWallet/Views/ImportSeedEditor.swift
- modules/Sources/Features/OnboardingFlow/PlainOnboardingView.swift
- modules/Sources/Features/Root/RootDebug.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
- modules/Sources/Features/Root/RootView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/UIComponents/TextFields/Components/TextFieldTitleAccessoryButtonStyle.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secantTests/RootTests/DebugTests.swift
Closes #793 
- fixed alerts in debug menu
- fixed confirmation dialog in for rescan action
- fixed dark mode colors
- updated texts
- simplified texteditor UI so it's more consistent with the other components
- reduced debug menu items
- adopted latest SDK with updated checkpoints so new wallets don't take too much time to sync
- tests fixed
> [#793] Polish debug menu and fix dark mode

- modules/Package.resolved
- modules/Package.swift
- modules/Sources/Dependencies/CrashReporter/CrashReporterInterface.swift
- modules/Sources/Dependencies/CrashReporter/CrashReporterLiveKey.swift
- modules/Sources/Dependencies/CrashReporter/CrashReporterTestKey.swift
- modules/Sources/Features/Root/RootDebug.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
- modules/Sources/Features/Root/RootView.swift
- modules/Sources/Features/Settings/SettingsStore.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- secantTests/RecoveryPhraseValidationTests/RecoveryPhraseValidationFlowFeatureFlagTests.swift
- secantTests/RootTests/AppInitializationTests.swift
- CrashReporter is now an independent module
- all crash reporter TODOs removed
- the crash reporter code commented out is now back in action
- adopted latest SDK
> [#747] CrashReporterClient as isolated package

- modules/Package.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secantTests/UtilTests/LoggerTests.swift
Closes #804 
- SDK version updated so the FFI is updated as well
- log levels changed so uni tests fixed
> [#804] Update FFI dependency

- modules/Package.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #810 
- hotfix for the CI to work again
> [#810] Bitrise fails to build

- modules/Sources/Dependencies/ZcashSDKEnvironment/ZcashSDKEnvironmentInterface.swift
Closes #814 
- endpoint updated to the latest and workable server
> [#814] Server update

- modules/Package.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #816 
- TCA updated to the latest supported version, there's a 1.0 release already but handled in a different ticket
> [#816] Adopt TCA 0.59.0

- modules/Package.swift
- modules/Sources/Dependencies/SDKSynchronizer/SDKSynchronizerInterface.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
- modules/Sources/Features/WalletEventsFlow/WalletEventsFlowStore.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/Models/AppDelegate.swift
- modules/Sources/Models/SyncStatusSnapshot.swift
- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/SecantApp.swift
- secantTests/RecoveryPhraseValidationTests/RecoveryPhraseValidationFlowFeatureFlagTests.swift
- secantTests/RootTests/AppInitializationTests.swift
- secantTests/RootTests/RootTests.swift
- secantTests/WalletEventsTests/WalletEventsTests.swift
Closes #826 
- wallet captures app's lifecycle notifications for background and foreground and appropriately responds to handle SDKSynchronizer
- tests fixed
- a few small UI tweaks (light appearance, ..)
> [#826] proper handling of apps lifecycle

- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
Closes #832 
- localized files updated, secant -> Zashi
> [#832] Replace user-facing Secant strings with Zashi

- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Update dependencies & version for 0.2.0 release.

- modules/Sources/Features/Home/HomeView.swift
Closes #839 
- balance on the home screen is now a total instead of verified one
> [#839] Show total balance on Home screen

- modules/.swiftpm/xcode/xcshareddata/xcschemes/UIComponents.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/Welcome.xcscheme
- modules/Package.swift
- modules/Sources/Features/OnboardingFlow/OnboardingFlowStore.swift
- modules/Sources/Features/OnboardingFlow/PlainOnboardingView.swift
- modules/Sources/Features/Root/RootDestination.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
- modules/Sources/Features/Root/RootView.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningView.swift
- modules/Sources/Features/Welcome/WelcomeView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/UIComponents/Buttons/CheckboxToggleStyle.swift
- modules/Sources/UIComponents/Buttons/ZashiBack.swift
- modules/Sources/UIComponents/Overlays/SplashView.swift
- secant.xcodeproj/project.pbxproj
- secantTests/RootTests/AppInitializationTests.swift
- secantTests/SnapshotTests/SecurityWarningSnapshotTests/SecurityWarningSnapshotTests.swift
Closes #841 
- custom toggle
- security screen UI and logic finished
- splash screen extended to report completion, this way I can assure it never shows again
- dynamic Zashi version + build implemented into the warning message
- snapshot tests added
> [#841] Warning screen

- modules/.swiftpm/xcode/xcshareddata/xcschemes/RecoveryPhraseDisplay.xcscheme
- modules/Package.swift
- modules/Sources/Features/Profile/ProfileView.swift
- modules/Sources/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayStore.swift
- modules/Sources/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayView.swift
- modules/Sources/Features/Sandbox/SandboxView.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift
- modules/Sources/Features/SendFlow/SendFlowView.swift
- modules/Sources/Features/Settings/SettingsStore.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/Models/RecoveryPhrase.swift
- secantTests/BackupFlowTests/RecoveryPhraseBackupTests.swift
- secantTests/BackupFlowTests/RecoveryPhraseDisplayReducerTests.swift
- secantTests/SettingsTests/SettingsTests.swift
- secantTests/SnapshotTests/RecoveryPhraseDisplaySnapshotTests/RecoveryPhraseDisplaySnapshotTests.swift
Closes #845 
- redesigned according to new Zashi UI
- modified grouping or phrase words, halves instead of quarters
- snapshot tests updated
- code cleanup - recovery phrase screen loads the stored wallet instead of being injected into it
> [#845] Recovery screen

- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [#853] open privacy policy from the security screen

- modules/.swiftpm/xcode/xcshareddata/xcschemes/OnboardingFlow.xcscheme
- modules/Sources/Features/OnboardingFlow/PlainOnboardingView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/UIComponents/Buttons/ZashiButton.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #856 
- Opening Screen UI has been redesigned according to the new Zashi UI
> [#856] Opening screen UI

- modules/.swiftpm/xcode/xcshareddata/xcschemes/Settings.xcscheme
- modules/Sources/Features/Settings/SettingsStore.swift
- modules/Sources/Features/Settings/Views/About.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Colors.xcassets/suppressed30.colorset/Contents.json
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/Generated/XCAssets+Generated.swift
- modules/Sources/UIComponents/Toolbar/ZashiBack.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #858 
- About screen updated to the Zashi UI
- back button finalised according to the Zashi UI
> [#858] About screen UI

- modules/Sources/Features/AddressDetails/AddressDetailsStore.swift
- modules/Sources/Features/Home/HomeStore.swift
- modules/Sources/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayView.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
- modules/Sources/Features/Tabs/TabsView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secantTests/HomeTests/HomeTests.swift
- secantTests/RootTests/RootTests.swift
Closes #861 
- error dialogs removed
- cleanup of the code
- sdk 2.0.2 adopted, version bumped
- error dialogs removed
- a few bugfixes:
- phrase display can handle longer words and still render it fully with no truncation
- tabs tap area increased
- receive screen with addresses now uses the wallet's UA
> [#861] Remove lightwalletd related error dialogs

- modules/Package.swift
- modules/Sources/Features/OnboardingFlow/PlainOnboardingView.swift
- modules/Sources/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayView.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningView.swift
- modules/Sources/Features/Settings/SettingsStore.swift
- modules/Sources/Features/Settings/SettingsView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/UIComponents/Buttons/ZashiButton.swift
- modules/Sources/UIComponents/Toolbar/ToolbarAction.swift
- secantTests/RootTests/AppInitializationTests.swift
- secantTests/SettingsTests/SettingsTests.swift
Closes #868 
- tap to copy phrase action added to the phrase screen
> [#868] tap to copy seed

- modules/Package.swift
- modules/Sources/Dependencies/NumberFormatter/NumberFormatterLiveKey.swift
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownView.swift
- modules/Sources/Features/Home/HomeView.swift
- modules/Sources/Features/OnboardingFlow/PlainOnboardingView.swift
- modules/Sources/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayView.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningView.swift
- modules/Sources/Features/SendFlow/Views/CreateTransactionView.swift
- modules/Sources/Features/SendFlow/Views/TransactionSendingView.swift
- modules/Sources/Features/Settings/SettingsStore.swift
- modules/Sources/Features/Settings/SettingsView.swift
- modules/Sources/Features/WalletEventsFlow/Views/TransactionDetailView.swift
- modules/Sources/Features/WalletEventsFlow/Views/TransactionRowView.swift
- modules/Sources/Features/WalletEventsFlow/Views/WalletEvent+View.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/UIComponents/Balance/BalanceTitle.swift
- modules/Sources/UIComponents/Buttons/ZashiButton.swift
- modules/Sources/UIComponents/Toolbar/ToolbarAction.swift
- modules/Sources/Utils/BalanceFormatter.swift
- modules/Sources/Utils/NumberFormatter+zcash.swift
- secantTests/RootTests/AppInitializationTests.swift
- secantTests/SettingsTests/SettingsTests.swift
- secantTests/UtilTests/ZatoshiTests.swift
Closes #870 
- BalanceTitle view created for the bigger balance + zcash icon
- balance formatter with 3 floating points created and used everywhere in the views
- tests for this formatted added to check bank rounding
> [#870] balance truncation to 3 floating points

- modules/.swiftpm/xcode/xcshareddata/xcschemes/ImportWallet.xcscheme
- modules/Package.swift
- modules/Sources/Dependencies/NumberFormatter/NumberFormatterLiveKey.swift
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- modules/Sources/Features/ExportLogs/ExportLogsStore.swift
- modules/Sources/Features/Home/HomeStore.swift
- modules/Sources/Features/ImportWallet/ImportBirthdayView.swift
- modules/Sources/Features/ImportWallet/ImportWalletStore.swift
- modules/Sources/Features/ImportWallet/ImportWalletView.swift
- modules/Sources/Features/ImportWallet/Views/ImportSeedEditor.swift
- modules/Sources/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayStore.swift
- modules/Sources/Features/Root/RootDebug.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
- modules/Sources/Features/Scan/ScanStore.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift
- modules/Sources/Features/SendFlow/SendFlowStore.swift
- modules/Sources/Features/Settings/SettingsStore.swift
- modules/Sources/Features/WalletEventsFlow/WalletEventsFlowStore.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/UIComponents/TextFields/TransactionAmount/TransactionAmountTextFieldStore.swift
- modules/Sources/UIComponents/ZashiLogo/ZashiLogo.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secantTests/ImportWalletTests/ImportWalletTests.swift
Closes #864 
- Fixes & UI enhancements for the birthday screen
- Layout updated to be scrollable for the seed screen
- Code cleanup
- SDK 2.0.3 adopted
> [#864] Restore from seed UI

- modules/Sources/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- modules/Sources/Models/TransactionState.swift
Closes #873 
- the TransactionState always require a BlockHeight to be given, no more optional
- This ensures transactions are properly evaluated for the state (pending vs. non-pending)
> [#873] Start of the app shows pending state for the transaction

- modules/Package.swift
- modules/Sources/Dependencies/DatabaseFiles/DatabaseFilesInterface.swift
- modules/Sources/Features/PrivateDataConsent/PrivateDataConsentStore.swift
- modules/Sources/Features/PrivateDataConsent/PrivateDataConsentView.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningView.swift
- modules/Sources/Features/Settings/SettingsStore.swift
- modules/Sources/Features/Settings/SettingsView.swift
- modules/Sources/Features/Tabs/TabsStore.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- secant.xcodeproj/project.pbxproj
- secantTests/PrivateDataConsentTests/PrivateDataConsentTests.swift
- secantTests/SettingsTests/SettingsTests.swift
- secantTests/SnapshotTests/PrivateDataConsentSnapshotTests/PrivateDataConsentSnapshotTests.swift
- secantTests/SnapshotTests/SettingsSnapshotTests/SettingsSnapshotTests.swift
Closes #885 
- PrivateDataConsent screen implemented where is possible to share the dataDb
- tests fixed + added
> [#885] Export of private data

- modules/Package.swift
- modules/Sources/Dependencies/ReadTransactionsStorage/ReadTransactionsStorageInterface.swift
- modules/Sources/Dependencies/ReadTransactionsStorage/ReadTransactionsStorageLiveKey.swift
- modules/Sources/Dependencies/ReadTransactionsStorage/ReadTransactionsStorageTestKey.swift
- modules/Sources/Features/Home/HomeStore.swift
- modules/Sources/Features/TransactionList/TransactionListStore.swift
- modules/Sources/Features/TransactionList/Views/TransactionHeaderView.swift
- modules/Sources/Generated/Resources/Assets.xcassets/flyReceivedFilled.imageset/Contents.json
- modules/Sources/Models/TransactionState.swift
- secant.xcodeproj/project.pbxproj
- secant/Resources/ReadTransactionsStorageModel.xcdatamodeld/TransactionReadUnreadM.xcdatamodel/contents
- secantTests/TransactionListTests/TransactionListTests.swift
- secantTests/TransactionListTests/TransactionStateTests.swift
Closes #888 
- implemented CoreData dependency as this is the best choice for the persistency in the end
- business logic in the TCA that handles read/unread state
- update the list only if there's anything new
- unit tests & fixes
> [#888] Read and unread state persistency for transactions

- modules/Sources/Features/TransactionList/TransactionListStore.swift
- secantTests/TransactionListTests/TransactionListTests.swift
Closes #898 
- fixed unread timestamp logic, old transactions are marked as read
- the BUG itself was in the unit test, that's why it got through the testing unnoticed
> [#898] Feature timestamp is broken in unread logic

- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- modules/Sources/Features/Home/HomeStore.swift
- modules/Sources/Features/Root/RootDebug.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Scan/ScanStore.swift
- modules/Sources/Features/TransactionList/TransactionListStore.swift
Closes #904 
- all commented out side effects refactored to the newest API
> [#904] Side effects refactor

- modules/Sources/Features/Root/RootDestination.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Scan/ScanStore.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningView.swift
- secant/SecantApp.swift
- secantTests/AddressDetailsTests/AddressDetailsTests.swift
- secantTests/BackupFlowTests/RecoveryPhraseDisplayReducerTests.swift
- secantTests/BalanceBreakdownTests/BalanceBreakdownTests.swift
- secantTests/DeeplinkTests/DeeplinkTests.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/ImportWalletTests/ImportWalletTests.swift
- secantTests/PrivateDataConsentTests/PrivateDataConsentTests.swift
- secantTests/RootTests/AppInitializationTests.swift
- secantTests/RootTests/RootTests.swift
- secantTests/ScanTests/ScanTests.swift
- secantTests/SendTests/SendTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/NotEnoughFeeSpaceSnapshots.swift
- secantTests/SnapshotTests/PrivateDataConsentSnapshotTests/PrivateDataConsentSnapshotTests.swift
- secantTests/SnapshotTests/SecurityWarningSnapshotTests/SecurityWarningSnapshotTests.swift
- secantTests/SnapshotTests/SettingsSnapshotTests/SettingsSnapshotTests.swift
- secantTests/TransactionListTests/TransactionListTests.swift
- secantTests/WalletConfigProviderTests/WalletConfigProviderTests.swift
Closes #905 
- tests refactored to MainActor async ones
- hosting application bypassed so the tests are passing and not flaky
- code cleanup
- snapshot tests with ViewStore bindings work again
> [#905] Unit tests refactor to async

- modules/Sources/Features/Root/RootDebug.swift
- modules/Sources/Features/Root/RootDestination.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
- modules/Sources/Features/Root/RootView.swift
- modules/Sources/UIComponents/Balance/Balance8FloatingDigitsView.swift
- modules/Sources/Utils/Bindings.swift
- modules/Sources/Utils/Logging/TCALogging.swift
- secantTests/RootTests/DebugTests.swift
- secantTests/RootTests/RootTests.swift
- secantTests/TransactionListTests/TransactionListTests.swift
Closes #908 
- Confirmation dialog refactored, used brand new navigation TCA pattern
> [#908] Confirmation dialog refactor

- modules/Sources/Features/TransactionList/Views/MessageView.swift
- modules/Sources/Features/TransactionList/Views/TransactionHeaderView.swift
- modules/Sources/Features/TransactionList/Views/TransactionIDView.swift
- modules/Sources/Generated/Resources/Colors.xcassets/messageBcgReceived.colorset/Contents.json
- modules/Sources/UIComponents/Balance/ZatoshiRepresentationView.swift
- secantTests/RootTests/WalletNukeTests.swift
- secantTests/TransactionListTests/TransactionListTests.swift
- secantTests/ZatoshiStringRepresentation/ZatoshiStringRepresentationTests.swift
Closes #922 
- message (memo) text regular weight, black color
- change the color or received message bubble background
- no message included... title regular + black
- transaction ID (expanded one) regular font + black
- expanded address regular font + black
> [#922] Batch of ux feedback tweaks

- README.md
This depends on [Electric-Coin-Company/zashi#1]
> Update the README for the Zashi iOS repository.

- CHANGELOG.md
- secant.xcodeproj/project.pbxproj
Closes #923 
- changelog updated to cover all new Zashi changes
> [#923] Changelog update

- CHANGELOG.md
- modules/Sources/Features/AddressDetails/AddressDetailsStore.swift
- modules/Sources/Features/AddressDetails/AddressDetailsView.swift
- secantTests/AddressDetailsTests/AddressDetailsTests.swift
> [#918] Omit sapling address

- modules/Sources/Dependencies/Deeplink/Deeplink.swift
- modules/Sources/Dependencies/WalletStorage/WalletStorage.swift
- modules/Sources/Features/Home/HomeStore.swift
- modules/Sources/Features/Root/RootDestination.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Settings/SettingsView.swift
- modules/Sources/UIComponents/DebugMenu.swift
- modules/Sources/UIComponents/TextFields/Components/CurrencySelection/CurrencySelectionStore.swift
- modules/Sources/UIComponents/TextFields/TransactionAmount/TransactionAmountTextFieldStore.swift
- secantTests/UtilTests/WalletStorageTests.swift
> [#919] Update todo to link ecc repo instead of secant

- CHANGELOG.md
- modules/Package.swift
- modules/Sources/Features/SendFlow/SendFlowStore.swift
- modules/Sources/Features/SendFlow/SendFlowView.swift
- modules/Sources/Features/Tabs/TabsStore.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- secantTests/SendTests/SendTests.swift
- secantTests/TabsTests/TabsTests.swift
Closes #930 
- the UX of the newly created transaction is improved by inserting the returned transaction immediately to the array of transactions, that way when the account page is accessed, the sending transaction is presented
- unit tests fixed + added new ones
> [#930] Newly created transaction

- CHANGELOG.md
- modules/Package.swift
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownView.swift
- modules/Sources/Features/Home/HomeView.swift
- modules/Sources/Features/SendFlow/SendFlowConfirmationView.swift
- modules/Sources/Features/SendFlow/SendFlowStore.swift
- modules/Sources/Features/SendFlow/SendFlowView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/UIComponents/Buttons/ZashiButton.swift
- secantTests/SendTests/SendTests.swift
- secantTests/SnapshotTests/SendSnapshotTests/TransactionSendingSnapshotTests.swift
Closes #936 
- confirmation screen implemented
- navigation flow implemented instead of just 1 pushed view
- uni tests fixed + added new ones that handles new actions and states
- zashi button modifier extended to offer new options for new states
> [#936] Send confirmation screen UI

- CHANGELOG.md
- modules/Sources/Features/AddressDetails/AddressDetailsStore.swift
- modules/Sources/Features/AddressDetails/AddressDetailsView.swift
- modules/Sources/Features/Root/RootView.swift
- modules/Sources/Features/Tabs/TabsStore.swift
- modules/Sources/Features/Tabs/TabsView.swift
- secantTests/AddressDetailsTests/AddressDetailsTests.swift
- secantTests/SnapshotTests/AddressDetailsSnapshotTests/AddressDetailsSnapshotTests.swift
Closes #950 
- the sapling address and its QR code are present only for the testnet builds
- unit tests resolved and tweaked a bit - TCA actions have been merged into 1 copyToPasteboard
- snapshot tests for both mainnet and testnet version to prove sapling is missing on mainnet
> [#950] Sapling address when testnet build

- CHANGELOG.md
Closes #965 
- entries for user facing changes/fixes/updates
> [#965] Changelog update for the fixes

- CHANGELOG.md
- modules/Package.swift
- modules/Sources/Dependencies/LogsHandler/LogsHandlerLive.swift
- modules/Sources/Dependencies/LogsHandler/LogsHandlerTest.swift
- modules/Sources/Features/PrivateDataConsent/PrivateDataConsentStore.swift
- modules/Sources/Features/PrivateDataConsent/PrivateDataConsentView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/Utils/LogStore.swift
- modules/Sources/Utils/Logging/TCALogging.swift
- modules/Sources/Utils/WalletLogger.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secantTests/PrivateDataConsentTests/PrivateDataConsentTests.swift
Closes #968 
- export of logs from the sdk implemented
- the logs have been split into 2 files - verbose and sync specific logs + metrics
- SDK dependency adopted
- unit tests fixed + added new ones
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about
code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).
> [#968] Share logs in private data sector

- CHANGELOG.md
- modules/Package.swift
- modules/Sources/Dependencies/LogsHandler/LogsHandlerLive.swift
- modules/Sources/Features/PrivateDataConsent/PrivateDataConsentStore.swift
- modules/Sources/Features/PrivateDataConsent/PrivateDataConsentView.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secantTests/PrivateDataConsentTests/PrivateDataConsentTests.swift
Closes #979 
- `isAcknowledged` flag is reset with every private data screen access
- the export buttons are disabled throughout the whole export + share phase
- the spinner is attached to the button that's exporting
- unit tests for all this new functionality added
> [#979] Export private data ux tweaks

- CHANGELOG.md
- modules/Sources/Features/SendFlow/SendFlowStore.swift
- modules/Sources/Features/SyncProgress/SyncProgressStore.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- secantTests/SendTests/SendTests.swift
Closes #991 
- The alert metadata fixed
> [#991] Send failed alert not localized

- CHANGELOG.md
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/UIComponents/Hintbox/HintBoxShape.swift
- secantTests/BalanceBreakdownTests/BalanceBreakdownTests.swift
- secantTests/SnapshotTests/BalanceBreakdownSnapshotTests/BalanceBreakdownSnapshotTests.swift
Closes #933 
- The hint box implemented
- Snapshot tests extended to cover the hint box case
- Unit tests for show/hide of the hint box implemented
- Code cleanup of the previous design for the hint box
> [#933] Shielding hint box

- CHANGELOG.md
- modules/Sources/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayView.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- secantTests/RootTests/AppInitializationTests.swift
- secantTests/RootTests/RootTests.swift
Closes #997 
- changelog update
- the keys missing error state has been tweaked to try 3 retry attempts because of unresponsiveness keychain API
- in case of true missing keys, the user is no longer locked on a splash screen but rather let land to the Account tab so the rest of the Zashi can be used
- unit tests fixed + implemented new ones for the 3-attempt retry logic
> [#997] Keys missing handling

- modules/Sources/Dependencies/SupportDataGenerator/SupportDataGenerator.swift
- secantTests/SettingsTests/SettingsTests.swift
Closes #999 
- Subject in the mail composer/generator fixed
- unit tests checking the subject + mailto implemented
> [#999] Update support mail metadata

- modules/Package.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #1002 
- SDK updated to the 2.0.6
> [#1002] Adopt SDK 2.0.6

- CHANGELOG.md
- modules/Package.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #1005 
- SDK version bumped up, 2.0.7 has brought some rust performance optimizations
> [#1005] Adopt SDK 2.0.7

- CHANGELOG.md
- modules/Package.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #1014 
- SDK version bumped with shielding fix
> [#1014] Adopt SDK 2.0.8

- modules/Sources/Features/TransactionList/TransactionListStore.swift
- modules/Sources/Models/TransactionState.swift
- secantTests/TransactionListTests/TransactionListTests.swift
Closes #1019 
- reduced duplication of the code by extracting the logic into the transaction itself
> [#1019] Extract sort logic into a function

- CHANGELOG.md
- modules/Sources/Features/Home/HomeView.swift
- modules/Sources/Features/Root/RootInitialization.swift
- secantTests/RootTests/RootTests.swift
Closes #1022
Closes #1006 
- Restore mode in the UI was missing when Zashi was deleted from an iPhone and reinstalled again.
- Syncing bar in the restore mode bottom padding.
- unit test refactored to cover the case
> [#1022] Restore UI not activated when app is deleted and reinstalled

- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownView.swift
Closes #1035 
- balances aligned for all formats possible
> [#1035] Align balances vertically on Balances tab

- modules/.swiftpm/xcode/xcshareddata/xcschemes/AddressDetails.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/AppVersion.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/AudioServices.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/BalanceBreakdown.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/Home.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/ImportWallet.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/OnboardingFlow.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/Profile.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/RecoveryPhraseDisplay.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/SendFlow.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/Settings.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/TransactionList.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/UIComponents 1.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/UIComponents.xcscheme
- modules/.swiftpm/xcode/xcshareddata/xcschemes/Welcome.xcscheme
- modules/Package.swift
- modules/Sources/Dependencies/BalanceFormatter/ZatoshiStringRepresentation.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/xcshareddata/xcschemes/secant-mainnet.xcscheme
- secant.xcodeproj/xcshareddata/xcschemes/secant-testnet.xcscheme
- secantTests/ZatoshiStringRepresentation/ZatoshiStringRepresentationCommaTests.swift
Closes #975 
- The Zatoshi decimals have been localized with respect to floating point style
- unit tests fixed + new set of comma tests implemented
> [#975] Localize the balances

- modules/Sources/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- modules/Sources/Dependencies/ZcashSDKEnvironment/ZcashSDKEnvironmentInterface.swift
- modules/Sources/Dependencies/ZcashSDKEnvironment/ZcashSDKEnvironmentLiveKey.swift
- modules/Sources/Dependencies/ZcashSDKEnvironment/ZcashSDKEnvironmentTestKey.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift
- modules/Sources/Features/SendFlow/SendFlowStore.swift
- secant/SecantApp.swift
- secantTests/SendTests/SendTests.swift
Closes #981 
- the fee is now checked and it's coming from the SDK
- unit test checking validity of the form when not enough Zatoshi for the fee has been implemented
- brand new concept of handling the SDK constants inside the TCA has been implemented, will greatly simplify cleanup of all reducers (see #1058)
> [#981] Send button disable check must include the fee

- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
Closes #1053 
- text has been updated
> [#1053] Improve successful restore message

- modules/Sources/Dependencies/WalletStorage/WalletStorage.swift
Closes #1068 
- Change of the setup of the keychain massively reduces the probability and frequency of cases when the keychain is required to provide data. Background task for the sync was the main producer of these attempts to read the data, the new flag allows BGTask to operate freely with no errors related to the keychain. Ultimate solution how to make it even better is covered in #1071, TODO added to the code.
> [#1068] False positive keysMissing detection

- modules/Sources/Features/Settings/Views/About.swift
> [#940] Set final privacy policy URL for iOS

- modules/Sources/Features/SendFlow/SendFlowConfirmationView.swift
- modules/Sources/Features/SendFlow/SendFlowStore.swift
- modules/Sources/Features/SendFlow/SendFlowView.swift
- modules/Sources/UIComponents/TextFields/MessageEditor/MessageEditor.swift
- modules/Sources/UIComponents/TextFields/MessageEditor/MessageEditorStore.swift
- modules/Sources/UIComponents/TextFields/SingleLineTextField.swift
- modules/Sources/UIComponents/TextFields/TCATextField/TCATextField.swift
- modules/Sources/UIComponents/TextFields/TransactionAddress/TransactionAddressTextField.swift
- modules/Sources/UIComponents/TextFields/TransactionAmount/TransactionAmountTextField.swift
- modules/Sources/UIComponents/TextFields/TransactionAmount/TransactionAmountTextFieldStore.swift
- secantTests/SendTests/SendTests.swift
- secantTests/SnapshotTests/SendSnapshotTests/TransactionSendingSnapshotTests.swift
Closes #1080 
- All bullet points from the parent ticket have been resolved
- The keyboard is not decimal one so users don't need to switch to numbers + it reduces cases when users fill in some alphabetical letters + it improved the UX with floating point comma vs. point
- Error handling fixed
- Max amount fix and rely on spendable balance
- Unit tests fixed
> [#1080] Send amount enhancements

- modules/Sources/Features/SendFlow/SendFlowStore.swift
- modules/Sources/Features/SendFlow/SendFlowView.swift
- modules/Sources/UIComponents/TextFields/MessageEditor/MessageEditor.swift
- modules/Sources/UIComponents/TextFields/MessageEditor/MessageEditorStore.swift
Closes #1060 
- MessageEditor updated to present disabled state in a different way
- Text in the memo is not persisted when the transparent address is used and MessageBox disabled
- New unit tests implemented and many more updated
> [#1060] Memo field behaviours for transparent address

- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
Closes #1082 
- Message for the transparent hint box updated
> [#1082] New shielding explanation copy

- CHANGELOG.md
- modules/.swiftpm/xcode/xcshareddata/xcschemes/SecurityWarning.xcscheme
- modules/Sources/Features/OnboardingFlow/OnboardingFlowStore.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- secantTests/SnapshotTests/SecurityWarningSnapshotTests/SecurityWarningSnapshotTests.swift
Closes #1051 
- Layout changes for the Security warning consent
- The screen has also been refactored to the latest TCA
- Unit tests fixed
NOTE: the screen has also been changed to scrollable due to smaller screens, see the attachments.
> [#1051] Crashlytics acknowledge

- CHANGELOG.md
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownView.swift
- modules/Sources/Features/Home/HomeStore.swift
- modules/Sources/Features/Home/HomeView.swift
- modules/Sources/Features/SendFlow/SendFlowStore.swift
- modules/Sources/Features/SendFlow/SendFlowView.swift
- modules/Sources/UIComponents/Balance/AvailableBalanceView.swift
Closes #1055 
- The available balance 0 scenario is now handled on a product/design level and the 0 is replaced with a progress view.
- There is some redundancy in the code that is going to be resolved in #1087 because it will require to implement a brand new reducer and stream subscriber, out of the scope of this issue.
- Changelog updated.
> [#1055] Handle unavailable AccountBalance

- modules/Sources/Features/SyncProgress/SyncProgressStore.swift
- modules/Sources/Features/SyncProgress/SyncProgressView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- secantTests/SyncProgressTests/SyncProgressTests.swift
Closes #931 
- Statuses updated according to the product/design requirements.
> [#931] Statuses of the sync process dependency

- modules/Sources/Dependencies/WalletStorage/WalletStorage.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningView.swift
- modules/Sources/Models/InitializationState.swift
- secant/AppDelegate.swift
- secantTests/RootTests/AppInitializationTests.swift
- secantTests/RootTests/RootTests.swift
Closes #1086 
- initialization pipeline updated to handle state when BGTask runs with fresh app start, in such case Zashi wait and doesn't try to initialize SDK -> no keychain error is triggered
NOTE: read [comment](https://github.com/Electric-Coin-Company/zashi-ios/issues/1086#issuecomment-1969071333) in the parent ticket for more info how I achived to fix the issue
> [#1086] Resolve interaction with the keychain for both fore and background app states

- secant/secant-mainnet-Info.plist
- secant/secant-testnet-Info.plist
Closes #1093 
Closes #1094 
Closes #1096 
- The URL scheme has been removed entirely from the project
> [#1093] Zashi-iOS audit Issue B

- modules/Sources/Features/Tabs/TabsView.swift
Closes #1124 
- The line has been added to all tabs excluding Account
> [#1124] Line above tab bar

- modules/Sources/Features/TransactionList/TransactionListView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
Closes #1110 
- UI updated to handle case when no transactions are available
> [#1110] No transactions fetched at start

- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
Closes #1121 
- text updated
- generated file updated
> [#1121] Hint box text update

- modules/Sources/Features/SendFlow/SendFlowStore.swift
Closes #1100 
- the boolean helpers updated to address some specific states
> [#1100] Insufficient funds when syncing and enabled Review button

- modules/Sources/Features/TransactionList/TransactionListView.swift
Closes #1103 
- Pull to refresh feature has never been required or designed by Product or Leadership, it was a temporary thing that helped during the development but has been completely replaced with reactive approach over the time.
> [#1103] Remove pull to refresh

- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
- secantTests/RootTests/AppInitializationTests.swift
- secantTests/RootTests/RestoreWalletTests.swift
- secantTests/RootTests/RootTests.swift
Closees #1106 
- storedWallet is no longer held in memory
> [#1106] Zashi-iOS audit Issue G

- CHANGELOG.md
- secant.xcodeproj/project.pbxproj
> [#1126] Release 1.0-3

- modules/Sources/Features/Tabs/TabsView.swift
Closes #1131
- The page style of the tab view removed, this way the gesture is no longer available.
> [#1131] Remove swipe gesture between tabs

- modules/Sources/Dependencies/BalanceFormatter/ZatoshiStringRepresentation.swift
- secant/SecantApp.swift
- secantTests/SnapshotTests/BalanceBreakdownSnapshotTests/BalanceBreakdownSnapshotTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeSnapshotTests.swift
- secantTests/SnapshotTests/PrivateDataConsentSnapshotTests/PrivateDataConsentSnapshotTests.swift
- secantTests/SnapshotTests/SettingsSnapshotTests/SettingsSnapshotTests.swift
Close #1136 
- All false positive tests have been resolved. Flakiness of the tests has been fixed by providing unimplemented dependencies to the right Stores.
> [#1136] Fix flaky tests

- CHANGELOG.md
- secant.xcodeproj/project.pbxproj
- secant/Resources/PrivacyInfo.xcprivacy
Closes #1133 
- I set the required keys & hopefully the right values according to doc (https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401)
> [#1133] Define NSPrivacyAccessedAPITypes

- CHANGELOG.md
- modules/Sources/Features/SendFlow/SendFlowView.swift
- modules/Sources/Features/Tabs/TabsView.swift
Closes #1135 
- The white blank area above the keyboard has been fixed
> [#1135] Keyboard toolbars

- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownView.swift
- modules/Sources/Features/Home/HomeStore.swift
- modules/Sources/Features/Root/RootDebug.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
- modules/Sources/Features/Scan/ScanStore.swift
- modules/Sources/Features/SendFlow/SendFlowStore.swift
- modules/Sources/Features/SyncProgress/SyncProgressStore.swift
- modules/Sources/Features/TransactionList/TransactionListStore.swift
- modules/Sources/Features/TransactionList/TransactionListView.swift
Closes #1141 
- The no transactions list has been disabled to not scroll
- The sync bar % was canceled on Balanced before it could gather data, the problem is about cancelation IDs not being unique, I updated all effect handles to be UUIDs
- Balances tab was rendering spendable balance instead of total balance
> [#1141] Bugfix batch

- modules/Sources/Features/SendFlow/SendFlowConfirmationView.swift
Closes #1140
- send & back buttons disabled when request is in progress
> [#1140] Disable send and back buttons

- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secantTests/BalanceBreakdownTests/BalanceBreakdownTests.swift
- secantTests/ZatoshiStringRepresentation/ZatoshiStringRepresentationCommaTests.swift
- secantTests/ZatoshiStringRepresentation/ZatoshiStringRepresentationTests.swift
> ProposalAPI-comments

- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownView.swift
- modules/Sources/Features/SendFlow/SendFlowStore.swift
- modules/Sources/Features/TransactionList/Views/TransactionFeeView.swift
- modules/Sources/Features/TransactionList/Views/TransactionRowView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/Models/TransactionState.swift
- secantTests/ZatoshiStringRepresentation/ZatoshiStringRepresentationCommaTests.swift
- secantTests/ZatoshiStringRepresentation/ZatoshiStringRepresentationTests.swift
Closes #1147 
- The transactions with nil fees show Typical Fee < 0.001
- When the fee is available, the value is used
- Tests fixed
> [#1147] Handle nil transaction fees

- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- modules/Sources/Features/ExportLogs/ExportLogsStore.swift
- modules/Sources/Features/ImportWallet/ImportWalletStore.swift
- modules/Sources/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayStore.swift
- modules/Sources/Features/Root/RootStore.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift
- modules/Sources/Features/SendFlow/SendFlowStore.swift
- modules/Sources/Features/ServerSetup/ServerSetupStore.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/Utils/ZcashError+DetailedMessage.swift
- secantTests/SendTests/SendTests.swift
Closes #1149 
- The alert views now show more detailed info about the error. Code + message + rust/service error info
- Unit tests fixed
> [#1149] Include rust error desc in the alert view

- CHANGELOG.md
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownView.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Settings/Views/About.swift
- secant.xcodeproj/project.pbxproj
> [#986] Release Zashi iOS version 1.0

- modules/Package.swift
- modules/Sources/Features/DeleteWallet/DeleteWalletStore.swift
- modules/Sources/Features/DeleteWallet/DeleteWalletView.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Settings/AdvancedSettingsStore.swift
- modules/Sources/Features/Settings/AdvancedSettingsView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
Closes #1036 
- Wipe wallet feature integrated into advanced settings
> [#1036] Wipe wallet in advanced settings

- CHANGELOG.md
- modules/Package.swift
- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #1154 
- SDK version bump
> [#1154] Release 1.0.2

- CHANGELOG.md
- modules/Package.swift
- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #1156 
- fix for a bug in note selection when sending to a transparent recipient
> [#1156] Release 1.0.3

- CHANGELOG.md
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownView.swift
- modules/Sources/Features/Home/HomeStore.swift
- modules/Sources/Features/SendFlow/SendFlowStore.swift
- modules/Sources/Features/TransactionList/Views/MessageView.swift
- modules/Sources/Features/TransactionList/Views/TapToCopyTransactionDataView.swift
- modules/Sources/Features/TransactionList/Views/TransactionRowView.swift
- secantTests/SettingsTests/SettingsTests.swift
Closes #1119 
Closes #1160
- Tap to Copy memo added
- Fix for the [#1119](https://github.com/Electric-Coin-Company/zashi-ios/issues/1119)
- Fixes for the transparent funds
- Tests fixed
> [#1160] Tweaks and fixes for zashi 1.0.3

- modules/Sources/Features/ImportWallet/ImportBirthdayView.swift
Closes #1167 
- the BD field is automatically focused
> [#1167] Autofocus birthday field in restore flow

- modules/Sources/Features/NotEnoughFreeSpace/NotEnoughFreeSpaceView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
Closes #1174 
- The UI has been updated according to the latest design
> [#1174] Final not enough free space UI

- modules/Package.swift
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownView.swift
- modules/Sources/Features/Home/HomeStore.swift
- modules/Sources/Features/Home/HomeView.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/SendFlow/SendFlowConfirmationView.swift
- modules/Sources/Features/SendFlow/SendFlowStore.swift
- modules/Sources/Features/SendFlow/SendFlowView.swift
- modules/Sources/Features/Tabs/TabsStore.swift
- modules/Sources/Features/WalletBalances/WalletBalancesStore.swift
- modules/Sources/Features/WalletBalances/WalletBalancesView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/UIComponents/Balance/AvailableBalanceView.swift
- secantTests/BalanceBreakdownTests/BalanceBreakdownTests.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/ReviewRequestTests/ReviewRequestTests.swift
- secantTests/SendTests/SendTests.swift
- secantTests/SnapshotTests/BalanceBreakdownSnapshotTests/BalanceBreakdownSnapshotTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeSnapshotTests.swift
- secantTests/SnapshotTests/SendSnapshotTests/TransactionSendingSnapshotTests.swift
- secantTests/TabsTests/TabsTests.swift
Closes #1087 
- The total and available balances have been extracted into separate and fully autonomous component used in 3 independent places (Account, Send and Balances)
- Code massively cleaned up
- Available balance underline logic + redirect to Balances
- Unit tests fixes
> [#1087] Total and available balances component

- modules/Sources/UIComponents/Balance/AvailableBalanceView.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #1179 
- The ZEC token name is now aligned with the value (both bold)
> [#1179] Bold token name in available balance

- CHANGELOG.md
- modules/Package.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
Closes #1173 
- The restoration of the wallet is persisted until it's done (up-to date/synced) at some point in the future
> [#1173] Persist info about restore until it is done

- CHANGELOG.md
- modules/Sources/Features/SyncProgress/SyncProgressView.swift
Closes #1185 
- The syncing label's height has been unified so whatever state we render, the progress bar stays on the same position.
> [#1185] Syncing frame in progress view

- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- secantTests/RootTests/AppInitializationTests.swift
- secantTests/RootTests/RestoreWalletTests.swift
- secantTests/RootTests/RootTests.swift
Closes #1189 
- All unused texts have been removed from the project
- Tests checked and fixed (missing dependencies)
> [#1189] Cleanup of unused translations

- modules/Package.swift
- modules/Sources/Features/Settings/AdvancedSettingsStore.swift
- modules/Sources/Features/Settings/AdvancedSettingsView.swift
- modules/Sources/Features/Settings/SettingsStore.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secantTests/SettingsTests/SettingsTests.swift
Closes #1191 
- The reducer has been refactored
- The Bindings have been refactored to not use deprecated API
- View has been refactored to not rely on ViewStore
- Dependency version have been bumped up in order to use latest TCA
> [#1191] Refactor AdvancedSettingsReducer to latest TCA

- modules/Sources/Features/DeleteWallet/DeleteWalletView.swift
- modules/Sources/Features/PrivateDataConsent/PrivateDataConsentView.swift
- modules/Sources/Features/SecurityWarning/SecurityWarningView.swift
- modules/Sources/UIComponents/Toggle/ZashiToggle.swift
> [#1194] Security warning make the text clickable as well to improve usability

- CHANGELOG.md
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
Closes #1193 
- The input field for the recovery phrase now shows the expected format in the placeholder.
> [#1193] Restore: update the copy inside the input field

- CHANGELOG.md
- modules/Sources/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- modules/Sources/Features/TransactionList/Views/TransactionRowView.swift
- modules/Sources/Models/TransactionState.swift
Closes #1195 
- The "no message in the transaction" is no longer rendered for transparent Recipients
> [#1195] Transaction History: remove No message included in transaction copy from expanded transparent

- CHANGELOG.md
> [#1208] Release 1.0.5-4

- CHANGELOG.md
- modules/Sources/Dependencies/ZcashSDKEnvironment/ZcashSDKEnvironmentInterface.swift
- modules/Sources/Dependencies/ZcashSDKEnvironment/ZcashSDKEnvironmentLiveKey.swift
- modules/Sources/Dependencies/ZcashSDKEnvironment/ZcashSDKEnvironmentTestKey.swift
- modules/Sources/Features/ServerSetup/ServerSetupStore.swift
- modules/Sources/Features/ServerSetup/ServerSetupView.swift
- modules/Sources/Features/SyncProgress/SyncProgressView.swift
- secant.xcodeproj/project.pbxproj
Closes #1218 
- We have added one more group of server options (zec.rocks) for increased coverage and reliability
- zec.rocks:443 is now default wallet option
> [#1218] Add zec rocks servers

- modules/Sources/Features/Root/RootInitialization.swift
Closes #1224 
- The detection of pressed button needed to be extended to cover the case with SecurityWarning screen. I got it button is pressed in one of two possible scenarios and only one was handled.
> [#1224] Bug in Create a New Wallet flow

- modules/Sources/Features/ServerSetup/ServerSetupView.swift
- modules/Sources/Features/Settings/AdvancedSettingsView.swift
Closes #1221 
- Automatically scroll to the selected server so even the one at the bottom of the list that is not visible will be scrolled to the visual area.
> [#1221] Scroll to selected server

- CHANGELOG.md
- modules/Sources/Features/ServerSetup/ServerSetupView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
Closes #1228 
- the button's title has been refactored
> [#1228] I have saved it button title refactor

- CHANGELOG.md
- modules/Package.swift
- modules/Sources/Dependencies/QRImageDetector/QRImageDetectorInterface.swift
- modules/Sources/Dependencies/QRImageDetector/QRImageDetectorLiveKey.swift
- modules/Sources/Dependencies/QRImageDetector/QRImageDetectorTestKey.swift
- modules/Sources/Features/Scan/ScanStore.swift
- modules/Sources/Features/Scan/ScanView.swift
- modules/Sources/Features/Scan/UIKitBridge/ZashiImagePicker.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
Closes #1231 
- The ZashiImagePicker implemented that opens a library and reads an image from it
- QR code image detector implemented
- QRImageDetector dependency implemented
- Multiple codes detection + handling. For it's an error because more codes could result in wrong pick from user's point of view.
- final design
> [#1231] QR code from a photo saved in my library

- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownView.swift
- modules/Sources/Features/Home/HomeView.swift
- modules/Sources/Features/WalletBalances/WalletBalancesView.swift
- modules/Sources/UIComponents/Balance/AvailableBalanceView.swift
- modules/Sources/UIComponents/Balance/BalanceWithIconView.swift
Closes #1252 
- fixes for some Balances (views) that must stay always visible even though the hide balances is turned on
> [#1252] Some views hide balances that is supposed to be visible

- modules/Sources/Features/Tabs/TabsView.swift
Closes #1250 
- The hide balances feature is supposed to be on Account and Balances tabs only so I removed it from Send and Receive
> [#1250] Restrict Hide balances to Account and Balances tabs only

- CHANGELOG.md
- modules/Sources/Dependencies/SDKSynchronizer/SDKSynchronizerInterface.swift
- modules/Sources/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- modules/Sources/Dependencies/SDKSynchronizer/SDKSynchronizerTest.swift
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- modules/Sources/Features/Scan/ScanStore.swift
- modules/Sources/Features/WalletBalances/WalletBalancesStore.swift
- modules/Sources/Generated/Resources/Colors.xcassets/messageBcgBorder.colorset/Contents.json
- modules/Sources/Generated/Resources/Colors.xcassets/messageBcgDisabled.colorset/Contents.json
- modules/Sources/Generated/XCAssets+Generated.swift
- modules/Sources/UIComponents/TextFields/MessageEditor/MessageEditor.swift
- secantTests/RootTests/AppInitializationTests.swift
- secantTests/ScanTests/ScanTests.swift
Closes #1254 
- The balances are proactively refreshed immediately after send or shield proposals are processed
- I also noticed wrong color of disabled message box when sending to transparent address so it's been fixed in this PR as well
> [#1254] Refresh balances immediately after send

- CHANGELOG.md
- secant.xcodeproj/project.pbxproj
Closes #1256
- Version updated to 1.1 build 3
> [#1256] Release 1.1-3

- modules/Sources/Utils/QRCodeGenerator.swift
Closes #1258 
- Due to inconsistencies of different QR readers we revert the QR code to standardised coluors
> [#1258] Share QR code lacks background

- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownView.swift
- modules/Sources/Features/SendFlow/SendFlowView.swift
- modules/Sources/Features/Tabs/TabsView.swift
Closes #1260 
- addressed comments and feedback, the send balances are hidden but not amounts
- the hide balances button is accessible on send screen
- shielding is disabled when balances are hidden
> [#1260] Tweak hide balances

- modules/Package.swift
- modules/Sources/Features/PartialProposalError/PartialProposalErrorStore.swift
- modules/Sources/Features/PartialProposalError/PartialProposalErrorView.swift
- modules/Sources/Features/SendConfirmation/SendConfirmationStore.swift
- modules/Sources/Features/SendConfirmation/SendConfirmationView.swift
- modules/Sources/Features/SendFlow/SendFlowStore.swift
- modules/Sources/Features/SendFlow/SendFlowView.swift
- modules/Sources/Features/Tabs/TabsStore.swift
- modules/Sources/Features/Tabs/TabsView.swift
- modules/Sources/UIComponents/Toolbar/ZashiBack.swift
- The logic for navigation has been redesigned so confirmation screen is taken out of the tab-view navigation. That allowed to use iOS 15 and biometric lock and avoid SwiftUI navigation bug
- This PR basically only changed the way how the views are presented and handled, the functionality stayed the same from a user's point of view
- This change fixed the problem view TEX addresses send and error being populated, the one also had a broken navigation
- The send tests are broken and will be fixed as a follow up task #1264 
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, …
> biometric--send

- CHANGELOG.md
- modules/Sources/Features/TransactionList/Views/MessageView.swift
- modules/Sources/Features/TransactionList/Views/TransactionRowView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- modules/Sources/Models/TransactionState.swift
Closes #1235 
- Multi-text memos implemented
> [#1235] When receiving a multi-output transaction all memos must be displayed

- CHANGELOG.md
- modules/Sources/Features/Settings/AdvancedSettingsStore.swift
- modules/Sources/Features/Settings/AdvancedSettingsView.swift
Closes #1234 
- Biometric lock if available is used to protect seed, delete zashi and export private data
- Also protecting Send at the very last step, when tapping the send button
> [#1234] improve security and authentication requirements

- CHANGELOG.md
- modules/Package.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #1267
- Fixed the crash of shielding, the error message is presented instead
> [#1267] Adopt sdk with shielding crash fix

- CHANGELOG.md
- modules/Sources/Features/BalanceBreakdown/BalanceBreakdownStore.swift
- modules/Sources/Features/Home/HomeStore.swift
- modules/Sources/Features/SyncProgress/SyncProgressStore.swift
- modules/Sources/Features/SyncProgress/SyncProgressView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
- secantTests/SyncProgressTests/SyncProgressTests.swift
Closes #1270 
- SyncProgress reducer has been refactored to the latest TCA
- Progress label is tappable when an error occurs and shows an alert view with the details
> [#1270] Synchronizer error in the alert view

- modules/Sources/Features/SendConfirmation/SendConfirmationStore.swift
- modules/Sources/Features/SendFlow/SendFlowStore.swift
Closes #1277 
- The reset form of send calls the right actions for the input fields to reset their local values as well
- When the biometric authentication fails the sending progress of buttons is reseted
> [#1277] Send failed authentication minor bugs

- CHANGELOG.md
- secant.xcodeproj/project.pbxproj
- secant/Resources/WhatsNew/whatsNew.json
Closes #1279 
- version set to 1.1.1-1
- Cleanup and fixes
> [#1279] Release 1.1.1

- secant/Resources/WhatsNew/whatsNew.json
Updated changelog for release version 1.1.2.
- [x ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ x] Does the code abide by the [Coding Guidelines](../blob/main/docs/CODING_GUIDELINES.md)?
> Updated whatsNew [1.1.2].json

- CHANGELOG.md
- secant.xcodeproj/project.pbxproj
Closes #1300 
- Project settings updated for version 1.1.2-1
> [#1300] Release 1.1.2-1

- modules/Package.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #1298 
- all dependencies have been bumped up to the latest versions
> [#1293] Dependencies update

- modules/.swiftpm/xcode/xcshareddata/xcschemes/Root.xcscheme
- modules/Sources/Features/Root/RootDebug.swift
- modules/Sources/Features/Root/RootDestination.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
- modules/Sources/Features/Root/RootView.swift
- secant/AppDelegate.swift
- secantTests/DeeplinkTests/DeeplinkTests.swift
- secantTests/RootTests/AppInitializationTests.swift
- secantTests/RootTests/DebugTests.swift
- secantTests/RootTests/RestoreWalletTests.swift
- secantTests/RootTests/RootTests.swift
- secantTests/RootTests/WalletNukeTests.swift
- secantTests/WalletConfigProviderTests/WalletConfigProviderTests.swift
Closes #1302 
- RootReducer has been refactored to the @Reducer Root
- All unit tests have been refactored as well
- Code cleanup
NOTE: this is tech dept task that has no visual impact on a user
> [#1302] Upgrade RootReducer to the latest TCA

- modules/Sources/Features/Home/HomeStore.swift
- modules/Sources/Features/Home/HomeView.swift
- modules/Sources/Features/Tabs/TabsStore.swift
- secantTests/HomeTests/HomeTests.swift
- secantTests/ReviewRequestTests/ReviewRequestTests.swift
- secantTests/SnapshotTests/HomeSnapshotTests/HomeSnapshotTests.swift
Closes #1304
- HomeReducer has been refactored to @Reducer Home
NOTE: this is tech dept task that has no visual impact on a user
> [#1304] Upgrade HomeReducer to the latest TCA

- modules/Sources/Features/Home/HomeStore.swift
- modules/Sources/Features/Sandbox/SandboxStore.swift
- modules/Sources/Features/TransactionList/TransactionListStore.swift
- modules/Sources/Features/TransactionList/TransactionListView.swift
- modules/Sources/Features/TransactionList/Views/MessageView.swift
- modules/Sources/Features/TransactionList/Views/TapToCopyTransactionDataView.swift
- modules/Sources/Features/TransactionList/Views/TransactionHeaderView.swift
- modules/Sources/Features/TransactionList/Views/TransactionIDView.swift
- modules/Sources/Features/TransactionList/Views/TransactionRowView.swift
- secantTests/SnapshotTests/TransactionListSnapshotTests/TransactionListSnapshotTests.swift
- secantTests/TransactionListTests/TransactionListTests.swift
Closes #1305 
- TransactionListReducer has been refactored to @Reducer TransactionList
NOTE: this is tech dept task that has no visual impact on a user
> [#1305] Upgrade TransactionListReducer to the latest TCA

- modules/Sources/Features/ExportLogs/ExportLogs.swift
- modules/Sources/Features/ExportLogs/ExportLogsStore.swift
- modules/Sources/Features/PrivateDataConsent/PrivateDataConsentStore.swift
- modules/Sources/Features/Root/RootStore.swift
Closes #1308 
- ExportLogsReducer has been refactored to @Reducer ExportLogs
> [#1308] Upgrade ExportLogsReducer to the latest TCA

- CHANGELOG.md
- modules/Sources/Features/TransactionList/TransactionListStore.swift
- modules/Sources/Features/TransactionList/Views/TransactionHeaderView.swift
- modules/Sources/Models/TransactionState.swift
Closes #1313 
- Changelog updated.
- Fixes for memos in the history, a yellow icon is back again and memos aren't unexpectedly missing or disappearing.
- [x Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
> [#1313] Missing memo in transaction history

- CHANGELOG.md
- modules/Package.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #1315 
- SDK version bumped up to 2.1.11
> [#1315] Adopt tx resubmission in SDK 2.1.11

- secant/Resources/WhatsNew/whatsNew.json
> Updated whatsNew.json for 1.1.3 release

- CHANGELOG.md
- secant.xcodeproj/project.pbxproj
Closes #1317 
- Project version set to 1.1.3-1
> [#1317] Release 1.1.3

- CHANGELOG.md
- modules/Package.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #1320 
- SDK version set to 2.1.12 with syncing fix.
- Changelog updated.
> [#1320] Adopt SDK with syncing fix

- CHANGELOG.md
- modules/Sources/Models/TransactionState.swift
Closes #1322
- Transactions marked as read are no longer rendered with a yellow icon.
- The value of unread is determined by isMarkedAsRead
> [#1322] Unread messages stay unread

- secant/Resources/WhatsNew/whatsNew.json
updated what's new for release 1.1.4
> Updated whatsNew.json

- CHANGELOG.md
- modules/Package.swift
- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Resources/WhatsNew/whatsNew.json
Closes #1338 
- SDK version bumped to 2.2.1
- Project setup updated to 1.1.5-1
> [#1338] Release 1.1.5-1

- CHANGELOG.md
- modules/Sources/Dependencies/ExchangeRate/ExchangeRateLiveKey.swift
- modules/Sources/Features/Root/RootDestination.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Tabs/TabsView.swift
- modules/Sources/UIComponents/Balance/ZatoshiRepresentationView.swift
- modules/Sources/UIComponents/HiddenIfSet/HiddenIfSet.swift
Closes #1360 
- Fixes for iOS 16 and older
> [#1360] Shared state is broken on older ios versions

- CHANGELOG.md
- modules/Sources/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- modules/Sources/Features/TransactionList/Views/TransactionHeaderView.swift
- modules/Sources/Models/TransactionState.swift
Closes #1379 
- A shield icon is no longer presented for received transactions to a transparent pool.
> [#1379] Improve the logic for displaying the shield icon in the Transaction History

- CHANGELOG.md
- modules/Package.swift
- modules/Sources/Features/SendConfirmation/SendConfirmationStore.swift
- modules/Sources/Features/SendFlow/SendFlowView.swift
- modules/Sources/Features/Tabs/TabsStore.swift
- modules/Sources/Models/RecoveryPhrase.swift
- modules/Sources/UIComponents/Overlays/SplashView.swift
- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Resources/WhatsNew/whatsNew.json
- Address book alias reset fix
- Request zec send navigation dismissal fix
- Feature flagging for the production build fixed
> Release 1.2.2 fixes

- modules/Sources/Models/FeatureFlags.swift
- secant/SecantApp.swift
- Feature flags are now initialized following specific build configs
> feature_flags_per_config

- CHANGELOG.md
- modules/Sources/Features/NotEnoughFreeSpace/NotEnoughFreeSpaceStore.swift
- modules/Sources/Features/NotEnoughFreeSpace/NotEnoughFreeSpaceView.swift
- modules/Sources/Features/Settings/AdvancedSettingsStore.swift
- modules/Sources/Features/Settings/AdvancedSettingsView.swift
- modules/Sources/Features/Settings/SettingsStore.swift
- modules/Sources/Features/Settings/SettingsView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/Localizable.strings
Closes #1367 
- The screen has been redesigned
NOTE: screen is forced to appear on a device with enough space, therefore values are "broken"
> [#1367] update UI of Not Enough Free Space status screen

- CHANGELOG.md
- modules/Sources/Features/Root/RootDestination.swift
Closes #1401 
- The navigation to the scanner is no longer blocked
> [#1401] Rescan in Zashi broken button

- modules/Package.resolved
- modules/Package.swift
- modules/Sources/Dependencies/WhatsNewProvider/WhatsNewProviderLiveKey.swift
- modules/Sources/Features/AddressBook/AddressBookView.swift
- modules/Sources/Features/PrivateDataConsent/PrivateDataConsentView.swift
- modules/Sources/Features/RecoveryPhraseDisplay/RecoveryPhraseDisplayView.swift
- modules/Sources/Features/Settings/SettingsStore.swift
- modules/Sources/Features/TransactionList/Views/TapToCopyTransactionDataView.swift
- modules/Sources/Features/TransactionList/Views/TransactionHeaderView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/en.lproj/Localizable.strings
- modules/Sources/Generated/Resources/es.lproj/Localizable.strings
- modules/Sources/UIComponents/Badges/PrivacyBadge.swift
- modules/Sources/UIComponents/TextFields/MessageEditor/MessageEditor.swift
- modules/swiftgen.yml
- secant.xcodeproj/project.pbxproj
- secant/Resources/WhatsNew/whatsNew_es.json
- secant/Resources/en.lproj/Localizable.strings
- secant/Resources/es.lproj/Localizable.strings
- secant/SecantApp.swift
> [#1239] Implement localization in spanish

- CHANGELOG.md
- modules/Sources/Dependencies/FlexaHandler/FlexaHandlerLiveKey.swift
Closes #1397 
- Flexa icon changed from Optional to strong reference in FlexaSDK, updated the code to fallback to blank image if the ZEC logo is not found
> [#1397] Release Zashi 1.2.3

- CHANGELOG.md
- modules/Package.swift
- modules/Sources/Dependencies/SupportDataGenerator/SupportDataGenerator.swift
- modules/Sources/Dependencies/WalletStorage/WalletStorage.swift
- modules/Sources/Features/OSStatusError/OSStatusErrorStore.swift
- modules/Sources/Features/OSStatusError/OSStatusErrorView.swift
- modules/Sources/Features/PartialProposalError/PartialProposalErrorView.swift
- modules/Sources/Features/Root/RootDestination.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
- modules/Sources/Features/Root/RootView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/en.lproj/Localizable.strings
- modules/Sources/Generated/Resources/es.lproj/Localizable.strings
- modules/Sources/Models/InitializationState.swift
- secant/Resources/en.lproj/Localizable.strings
- secant/Resources/es.lproj/Localizable.strings
Closes #1419 
Closes #1414 
- OSStatusError screen implemented
- Navigation + detection done
- added contact support button
- The texts have been localized
- A few text changes done even outside work on the initial task
- Final design resolved
> [#1419] Status page for keychain read failure

- modules/Sources/Dependencies/WalletStorage/WalletStorage.swift
- modules/Sources/Features/Root/RootInitialization.swift
- Pacu reported issue during testing and it was a case I missed during the OSStatus error screen work, this is the fix
- [x ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a …
> secItemNotFound error handling

- CHANGELOG.md
> [#1398] Zashi Release 1.2.4

- secant/Resources/WhatsNew/whatsNew.json
Updated Whats New_EN for 1.3.3 release
> Updated  whatsNew.json

- secant/Resources/WhatsNew/whatsNew_es.json
Updated Whats New_ES for 1.3.3 release
> Updated whatsNew_es.json

- CHANGELOG.md
> [#1470] Release 1.4

- CHANGELOG.md
- secant/AppDelegate.swift
Closes #1463 
- The TCA's side effect must be called on a main thread to avoid concurrency clash
> [#1463] Crash of background task

- CHANGELOG.md
> [#1480] Release 1.5

- CHANGELOG.md
- modules/Package.swift
- modules/Sources/Features/Receive/ReceiveView.swift
- modules/Sources/Features/Tabs/TabsStore.swift
- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Resources/WhatsNew/whatsNew.json
- secant/Resources/WhatsNew/whatsNew_es.json
> [#1483] Release 1.5.1

- CHANGELOG.md
- modules/Sources/Features/SendConfirmation/SendConfirmationStore.swift
- modules/Sources/Features/SendFeedback/SendFeedbackView.swift
- modules/Sources/Generated/L10n.swift
- modules/Sources/Generated/Resources/en.lproj/Localizable.strings
- modules/Sources/Generated/Resources/es.lproj/Localizable.strings
- secant.xcodeproj/project.pbxproj
- secant/Resources/WhatsNew/whatsNew.json
- secant/Resources/WhatsNew/whatsNew_es.json
- secant/Resources/en.lproj/Localizable.strings
- secant/Resources/es.lproj/Localizable.strings
> [#1487] Release 1.5.3

- CHANGELOG.md
- modules/Package.swift
- modules/Sources/Dependencies/SDKSynchronizer/SDKSynchronizerInterface.swift
- modules/Sources/Dependencies/SDKSynchronizer/SDKSynchronizerLive.swift
- modules/Sources/Dependencies/SDKSynchronizer/SDKSynchronizerTest.swift
- modules/Sources/Features/CoordFlows/RequestZecCoordFlowCoordinator.swift
- modules/Sources/Features/CoordFlows/RequestZecCoordFlowStore.swift
- modules/Sources/Features/CoordFlows/ScanCoordFlowCoordinator.swift
- modules/Sources/Features/CoordFlows/SendCoordFlowCoordinator.swift
- modules/Sources/Features/Home/HomeStore.swift
- modules/Sources/Features/Home/HomeView.swift
- modules/Sources/Features/Receive/ReceiveStore.swift
- modules/Sources/Features/Root/RootCoordinator.swift
- modules/Sources/Features/Root/RootInitialization.swift
- modules/Sources/Features/Root/RootStore.swift
- modules/Sources/Features/Settings/IntegrationsStore.swift
- modules/Sources/Features/Settings/SettingsCoordinator.swift
- modules/Sources/Features/Settings/SettingsStore.swift
- modules/Sources/Models/WalletAccount.swift
- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Code refactored
- Each Receive screen access generates a new private UA (= the one without transparent receivers)
> ua-without-a-transparent-receiver

- CHANGELOG.md
- secant.xcodeproj/project.pbxproj
- secant/Resources/WhatsNew/whatsNew.json
- secant/Resources/WhatsNew/whatsNew_es.json
> [#1504] Release 2.0.3

- CHANGELOG.md
Closes #1535 
- Swap with Near logic, release 2.2
> [#1535] Release 2.2

- CHANGELOG.md
- modules/Package.swift
- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Resources/WhatsNew/whatsNew.json
- secant/Resources/WhatsNew/whatsNew_es.json
> [#1537] Release 2.2.1

- CHANGELOG.md
- modules/Package.swift
- modules/Sources/Dependencies/UserMetadataProvider/UserMetadataStorage.swift
- modules/Sources/Features/SwapAndPayForm/SwapAndPayStore.swift
- modules/Sources/Features/TransactionDetails/TransactionDetailsView.swift
- secant.xcodeproj/project.pbxproj
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Resources/WhatsNew/whatsNew.json
- secant/Resources/WhatsNew/whatsNew_es.json
> [#1545] Release 2.4.1

- CHANGELOG.md
- modules/Package.swift
- secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- secant/Resources/WhatsNew/whatsNew.json
- secant/Resources/WhatsNew/whatsNew_es.json
Closes #1551 
- Whats new updated
> [#1551] Release 2.4.2
